### ISSUE TITLE
Remove support for unsigned candidate builds

### ISSUE THREAD

**Issue by davehunt** [mozilla/mozdownload#108]
I have been unable to find any unsigned candidate builds. Are we still building these? If not, we should remove this code-path from mozdownload.

**Comment by TLemur** [comment]
Is this still actual?

**Comment by whimboo** [comment]
Looking at the latest beta and release candidate builds I do not see this subfolder. So yes, we should be fine to get this removed.

http://ftp.mozilla.org/pub/mozilla.org/firefox/candidates/39.0b2-candidates/build1/
http://ftp.mozilla.org/pub/mozilla.org/firefox/candidates/38.0.5-candidates/build4/

**Comment by whimboo** [comment]
PR #288 fixed this issue.
