### ISSUE TITLE
Add support for downloading Fennec (Firefox Mobile) builds

### ISSUE THREAD

**Issue by davehunt** [mozilla/mozdownload#112]
Releases: https://ftp.mozilla.org/pub/mozilla.org/mobile/releases/
Candidates: https://ftp.mozilla.org/pub/mozilla.org/mobile/candidates/
Tinderbox: https://ftp.mozilla.org/pub/mozilla.org/mobile/tinderbox-builds/
Daily: https://ftp.mozilla.org/pub/mozilla.org/mobile/nightly/

**Comment by ncalexan** [comment]
I would like to help mentor this as well.  This could be part of https://bugzilla.mozilla.org/show_bug.cgi?id=1124378.

**Comment by Nebelhom** [comment]
@davehunt @ncalexan 

Is fennec's directory structure similar to one of the builds we already use (e.g. B2G or firefox)? I am just curious if it is a whole portion of code or more of a small change to a couple of lines of code...

**Comment by davehunt** [comment]
They certainly appear to be similar, but I'm not familiar enough to say with confidence.

**Comment by ncalexan** [comment]
Yes, similar if not identical.  At the end of the day, the packaging code
is the same -- `packager.{mk,py}` and `upload-files.mk`.  There tweaks to
the filename but the locale hierarchy, package name root, etc should follow
the pattern.

**Comment by whimboo** [comment]
Not sure if it is helpful right now to spend time on this issue. We are going to have to move to S3 for downloading builds soon. See issue #278. Maybe we can get this for free then without having to code that much as we would have to do now.

**Comment by dminor** [comment]
I'm planning to migrate mozbench to using mozdownload and need fennec support for that, so I'm planning to work on this.

**Comment by dminor** [comment]
Since mozbench only needs 'daily' builds, I'm only going to add support for that, rather than put in a bunch on effort that may have been unnecessary after we move to S3.

**Comment by whimboo** [comment]
That sounds totally fine. Thanks Daniel!

**Comment by whimboo** [comment]
Via PR #292 we got support for downloading Fennec daily builds. I will keep this issue open for the remaining build types. Thanks Dan for the new feature!

**Comment by whimboo** [comment]
Fenix support has actually been added via https://github.com/mozilla/mozdownload/issues/624 and is available in the latest mozdownload release. Marking as dupe.
