### ISSUE TITLE
Re-structure run_test.sh venv installation

### ISSUE THREAD

**Issue by Nebelhom** [mozilla/mozdownload#131]
This was observed in mozfile:
https://github.com/mozilla/mozbase/blob/master/mozfile/setup.py#L23

This change to using `python setup.py` would solve an issue in `run_tests-sh` with regard to the pip install section.

---

This issue originates from a previous comment in a different PR ( https://github.com/mozilla/mozdownload/pull/95/files#r5856846 )

This issue depends on pull #95

**Comment by son-vyas** [comment]
I am new to the mozilla community. Is this issue still active? If it is active than I would like to give it a go.

**Comment by whimboo** [comment]
I actually checked this issue, and due to the work on #468 we will get rid of both mozfile and mozhttpd. As such I don't think this issue is needed anymore.

@son-vyas you could have a look at issue #247.
