### ISSUE TITLE
Investigate depending on (or merging in) getb2g for support of B2G builds

### ISSUE THREAD

**Issue by davehunt** [mozilla/mozdownload#135]
We should see if we can depend on (or even merge) @ahal's https://github.com/ahal/getb2g project into mozdownload. Currently we are close to supporting the desktop builds, however getb2g supports device, desktop, and emulator builds. It would be awesome to have this support in mozdownload.

**Comment by whimboo** [comment]
B2g is officially dead. So I don't see a reason why we have to spend time on that. For connected devices builds we might want to have a new issue once necessary.
