### ISSUE TITLE
TinderboxScraper: Omit folders without binaries

### ISSUE THREAD

**Issue by Nebelhom** [mozilla/mozdownload#143]
Issue #11 implemented in the DailyScraper that empty folders are omitted from the binary search.

We would need this for the TinderboxScraper, too.

Here is a current test and its traceback:

`mozdownload -a firefox -t tinderbox -p linux --branch=mozilla-central`

`Retrieving list of builds from https://ftp.mozilla.org/pub/mozilla.org/firefox/tinderbox-builds/mozilla-central-linux
Found 209 builds: 1374305748, 1374398028, 1374400923, 1374487346, 1374500811 ... 1377562603, 1377562784, 1377569268, 1377583063, 1377597721
Traceback (most recent call last):
  File "scraper.py", line 960, in <module>
    cli()
  File "scraper.py", line 957, in cli
    build.download()
  File "scraper.py", line 237, in download
    if os.path.isfile(os.path.abspath(self.target)):
  File "scraper.py", line 197, in target
    self.build_filename(self.binary))
  File "scraper.py", line 148, in binary
    self.path)
__main__.NotFoundError: Binary not found in folder: https://ftp.mozilla.org/pub/mozilla.org/firefox/tinderbox-builds/mozilla-central-linux/1377597721`

A related issue is also the current failure to download a file with the `txt` extension which is also most likely down to this problem.

**Comment by Nebelhom** [comment]
@whimboo 

I am looking for a good test case, but I cannot find a recent folder that is still empty.

Any suggestions?

**Comment by whimboo** [comment]
This might be very hard to find. Maybe directly create testcases for mozhttpd?

**Comment by Nebelhom** [comment]
@whimboo I was worried about that option. It means that I have to rely on a test case that I wrote ;)

It's ok though, I managed to mimic it now. Let's see if I get anywhere with it.

**Comment by whimboo** [comment]
PR #242 has been merged and this will be in the 1.13 release now!
