### ISSUE TITLE
Refactoring of download with retry support

### ISSUE THREAD

**Issue by ghost** [mozilla/mozdownload#146]
There are many places in code which require to download something from remote server.
Moreover, we support case when timeout occurred and then we retry downloading of information.
However, in current state it's really ugly implemented (by many while True) and should be changed into something more readable (contextmanager?) and managable as a pattern.

**Comment by parkouss** [comment]
This is exactly the goal of the redo package I would say: https://pypi.python.org/pypi/redo

I have opened a PR using it, #342.

The output is slightly different, e.g if I raise an exception to try it intentionally:
```
mozdownload --type=daily --branch=mozilla-aurora --platform=win32 --retry-attempts=3
 INFO | Retrieving the build status file from https://archive.mozilla.org/pub/firefox/nightly/latest-mozilla-aurora/
 INFO | Retrieving list of builds from https://archive.mozilla.org/pub/firefox/nightly/2015/11/
 INFO | Found 1 build: 2015-11-08-00-40-59-mozilla-aurora
 INFO | Selected build: 2015-11-08-00-40-59-mozilla-aurora
 INFO | Downloading from: https://archive.mozilla.org/pub/firefox/nightly/2015/11/2015-11-08-00-40-59-mozilla-aurora/firefox-44.0a2.en-US.win32.installer.exe
 INFO | Saving as: /home/jp/dev/mozdownload/2015-11-08-00-40-59-mozilla-aurora-firefox-44.0a2.en-US.win32.installer.exe
 INFO | retry: Calling <function _download at 0x7fad39b54b18> with args: (), kwargs: {}, attempt #2
 INFO | retry: Calling <function _download at 0x7fad39b54b18> with args: (), kwargs: {}, attempt #3
 INFO | retry: Calling <function _download at 0x7fad39b54b18> with args: (), kwargs: {}, attempt #4
 INFO | retry: Giving up on <function _download at 0x7fad39b54b18>
Traceback (most recent call last):
  File "/home/jp/.virtualenvs/mozdownload/bin/mozdownload", line 9, in <module>
    load_entry_point('mozdownload==1.19', 'console_scripts', 'mozdownload')()
  File "/home/jp/dev/mozdownload/mozdownload/cli.py", line 168, in cli
    build.download()
  File "/home/jp/dev/mozdownload/mozdownload/scraper.py", line 313, in download
    errors.TimeoutError))
  File "/home/jp/dev/mozdownload/mozdownload/scraper.py", line 137, in _retry
    return redo.retry(func, **retry_kwargs)
  File "/home/jp/.virtualenvs/mozdownload/lib/python2.7/site-packages/redo/__init__.py", line 152, in retry
    return action(*args, **kwargs)
  File "/home/jp/dev/mozdownload/mozdownload/scraper.py", line 268, in _download
    raise errors.TimeoutError
mozdownload.errors.TimeoutError: The download exceeded the allocated timeout
```

You may not like it - tell me what you think!

**Comment by whimboo** [comment]
So what exactly caused us to redo the download in the above case? I wonder what the real issue here is and if that is hidden behind the timeout exception.

**Comment by parkouss** [comment]
Oh, no I broke the code intentionally to show that case, by adding "raise TimeoutError" somewhere.

**Comment by whimboo** [comment]
Ah, not the best exception class then. ;) But now it's clear.

So this line:

> Calling <function _download at 0x7fad39b54b18> w

Is that coming from the redo package? I wonder why they print the method and not it's name.

**Comment by parkouss** [comment]
yep, not sure why, but this is redo: https://github.com/bhearsum/redo/blob/master/redo/__init__.py#L151

I believe we can open a PR for that, to get it fixed if the author like the idea.

**Comment by whimboo** [comment]
Sounds like a good idea and I believe Ben will be open for that enhancement which gives better output for users on stdout. So yeah, I'm happy with the above changes and interested to see the PR. :)

**Comment by parkouss** [comment]
great, just opened https://github.com/bhearsum/redo/issues/35.
