### ISSUE TITLE
Misnomer: scraper.platform_regex is not a regex

### ISSUE THREAD

**Issue by Nebelhom** [mozilla/mozdownload#154]
The platform_regex attribute is chosen via

> return PLATFORM_FRAGMENTS[self.platform]

and the values in PLATFORM_FRAGMENTS are all just strings. Not a regular expression at all.

see https://github.com/mozilla/mozdownload/blob/master/mozdownload/scraper.py#l202

We should give a different name to `platform_regex`. The name is misleading.

**Comment by whimboo** [comment]
PR #233 has been merged.
