### ISSUE TITLE
"all" locales support for Release/Candidate Scrapers

### ISSUE THREAD

**Issue by ghost** [mozilla/mozdownload#164]
As overall work done for #118 is a little to big for review i've reconsidered to split this into smaller parts which should be easier for review.
First thing i want implement it's a suport of all locales and option of show available locales only for release/candidate scrapper as a first batch of changes.

**Comment by rv404674** [comment]
Hi @whimboo  is this bug still open and under active development. If yes, can you guide me how to approach it.

**Comment by whimboo** [comment]
No, I was just closing issue #118 because it is a feature we don't actually want to have anymore.

But something good to fix would be issue #492. This test is currently broken and needs a fix.

**Comment by rv404674** [comment]
Thanks for your help. But one more question, i am a newcomer, have just
build the firefox code. So can you suggest me some new comers bug in
python, i tried codetribute. But some were very much old and has no active
reporter. So can you suggest me on how to proceed.

**Comment by whimboo** [comment]
Please note that mozdownload is a separate project, and useful for those who want to download specific binaries of Firefox. It is used in various projects of Mozilla. So you are very welcome to pick one of the mentored issues on this repository (https://github.com/mozilla/mozdownload/issues?q=is%3Aopen+is%3Aissue+label%3Amentored). 

For a better discussion of a possible issue, let me know via email of a possible candidate. Then we don't have an off-topic discussion on this issue. Thanks.
