### ISSUE TITLE
Name of downloaded stub installer is not marked as such

### ISSUE THREAD

**Issue by Nebelhom** [mozilla/mozdownload#167]
When downloading a stub installer by using, for example,

`mozdownload -p win32 -v latest --stub`

The downloaded filename does not have a 'stub' in the name. The name should be different from the standard installer.

**Comment by whimboo** [comment]
Interesting that we already had the correct behavior for daily builds. Only release and candidate builds were missing it.

**Comment by whimboo** [comment]
PR #279 got merged for 1.15 release.
