### ISSUE TITLE
tinderbox builds selected using human-readable date have no unique file name

### ISSUE THREAD

**Issue by aleksejrs** [mozilla/mozdownload#181]
If I use  "-t tinderbox --date=1383739795", the "1383739795" is preprended instead of the ordinary date.
If I use "-t tinderbox --date=2013-11-06 [-build-num=3]", the file name is not changed, so it is not unique at all.

**Comment by whimboo** [comment]
I hit this again today and its indeed somewhat annoying. @Nebelhom is that anything you would be interested in fixing? :)
