### ISSUE TITLE
Failure in downloading builds due to timezone difference

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozdownload#193]
I wanted to download the build from:
Index of /pub/mozilla.org/firefox/nightly/2013/12/2013-12-01-mozilla-central-debug

It has been build right before midnight and its build id is 20131130032017. Downloading the build via the --build-id gives a failure:

$ mozdownload -t daily --debug --build-id 20131130032017
Retrieving list of builds from https://ftp.mozilla.org/pub/mozilla.org/firefox/nightly/2013/11/
Traceback (most recent call last):
  File "/Volumes/data/envs/m2d/bin/mozdownload", line 8, in <module>
    load_entry_point('mozdownload==1.8', 'console_scripts', 'mozdownload')()
  File "/Volumes/data/envs/m2d/lib/python2.7/site-packages/mozdownload/scraper.py", line 969, in cli
    build = BUILD_TYPES[options.type](**kwargs)
  File "/Volumes/data/envs/m2d/lib/python2.7/site-packages/mozdownload/scraper.py", line 311, in **init**
    Scraper.**init**(self, _args, *_kwargs)
  File "/Volumes/data/envs/m2d/lib/python2.7/site-packages/mozdownload/scraper.py", line 108, in **init**
    self.get_build_info()
  File "/Volumes/data/envs/m2d/lib/python2.7/site-packages/mozdownload/scraper.py", line 328, in get_build_info
    self.date, has_time=True)
  File "/Volumes/data/envs/m2d/lib/python2.7/site-packages/mozdownload/scraper.py", line 404, in get_build_info_for_date
    raise NotFoundError(message, url)
mozdownload.scraper.NotFoundError: Folder for builds on 2013-11-30-03-20-17 has not been found: https://ftp.mozilla.org/pub/mozilla.org/firefox/nightly/2013/11/

**Comment by whimboo** [comment]
This issue is actually kinda old, and a lot has been changed meanwhile in build generation and upload. So it might not happen anymore, or is less severe as it has been when the issue was filed.

I would suggest that we don't spend our time on that issue anymore and just close it.

@ranjanp75 if you want to work on something else please let me know. Thanks!

**Comment by ranjanp75** [comment]
Hi Henrik,

I am skilled in Python and I would love to work on the components which is
built with Python. Thank you

Regards,
Ranjan P

**Comment by ranjanp75** [comment]
Hey,

Yes I would love to work on it . But I need some help with it because I am
new to open source and I want to start contributing. Please guide me
through the process. Thank you.


Thanks & Regards,
Ranjan

**Comment by whimboo** [comment]
So please lets move all the conversation to the appropriate issue. It doesn't make sense to discuss it here.
