### ISSUE TITLE
Change our current progressbar package

### ISSUE THREAD

**Issue by Nebelhom** [mozilla/mozdownload#211]
Our current progressbar library is not maintained any more (last update 2011), has some shortcomings with regards to unknown file sizes (see #194 ) and is not easily extendible.

It might be best to switch to a new library here and while we're at it, maybe take a lightweight one that is easily extendible and fit it to our needs.

Whimboo has already made a suggestion:

https://pypi.python.org/pypi/progress/1.2

Last update was Nov 2013, it looks fairly lightweight and for our most current issue, it has the option of using a spinner instead of a progressbar, if we do not know the file size.

Are there any other suggestions? We could always start from scratch... but I, at least, realistically cannot guarantee that I will have consistently time to write a completely new package. If anyone else fancies that, feel free to comment.

**Comment by Nebelhom** [comment]
@whimboo @davehunt 

FYI.

Looks like someone picked up the old progressbar package, forked it from the source and carried it on.

https://pypi.python.org/pypi/progressbar2

**Comment by whimboo** [comment]
Yeah, I noticed that again today after forgetting about your comment. Looks like we have another chance! Maybe lets see what's new and if it helps us.

**Comment by whimboo** [comment]
Nice. It may be good to check that out. Labeling issue as mentored in case someone has interest to look at this.

**Comment by whimboo** [comment]
There is also https://github.com/tqdm/tqdm, but maybe we should just change to progressbar2, and upgrade to its latest release. It's still under active development.

**Comment by nathanielnebel** [comment]
I would be interested in working on this bug, would it still be possible to receive mentoring?

**Comment by whimboo** [comment]
Hello @nathanielnebel. Sure, this issue is still available to pick up. And I'm happy to mentor.

Given the still open question of what to use, I would say we keep progressbar and update it to progressbar2. There should be minimal efforts necessary to do that, and would be a good starting point for you.

Let me know what kind of issues you have or if something is not clear. I will respond as soon as I can. Thanks!

**Comment by nathanielnebel** [comment]
Changes are in pull request# 452.

**Comment by whimboo** [comment]
Hi @nathanielnebel. Thank you for doing the work, and it's good to hear that we don't need any changes in our code. I will have a look at your PR in a moment.

**Comment by whimboo** [comment]
PR #453 got merged now.

**Comment by whimboo** [comment]
@nathanielnebel in case you are interested to contribute a bit more please let me know and we can certainly find a new issue for you, or maybe you can find yourself from the list of open ones.

**Comment by nathanielnebel** [comment]
@whimboo If there are any issues that you think would be important to resolve let me know and I will get to work on some fixes!

**Comment by whimboo** [comment]
@nathanielnebel, issue #400 is for our unit tests, but it would be good to see it fixed. In case you are generally interested in Python we also have other interesting projects which could need a helping hand. You could drop me an email in case we should figure out something else.
