### ISSUE TITLE
test_direct_scraper.py should make use of local http server and not mozqa.com

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozdownload#214]
Right now the given tests wants to download a file from mozqa.com. It should really get if from the locally served pages via mozhttpd.

**Comment by jasonwist** [comment]
Yeah, it's been a while since I was looking at this (new job + being sick). 

Where can I find mozhttpd? I can see it being imported/used in mozhttpd_base_test but I can't find the where it (mozhttpd) and it's methods are defined.

**Comment by whimboo** [comment]
The document root of the server always points to `/tests/data`, so what you need in the test is self.wdir as defined here: https://github.com/mozilla/mozdownload/blob/master/tests/mozhttpd_base_test.py#L43

Here an example in how to use the local web server for serving content:
https://github.com/mozilla/mozdownload/blob/master/tests/base_scraper/test_base_scraper.py#L33

Please let me know if you have further questions.

**Comment by jasonwist** [comment]
How can I test to see if my changes have worked?

**Comment by whimboo** [comment]
There is a `run_tests.py` script in the root folder of the repository. Just run it and you will see if all the tests will pass, or if a failure is around for your changes.

**Comment by jasonwist** [comment]
I tried to inherit self.wdir from mhttpd_base_test (how I assume BaseScraperTest was getting access to it) but that wasn't working, so now I'm implementing all the steps to get wdir in TestDirectScraper. 

Was I on the right path before?

Also why does urljoin() use 'download_test.txt' in BaseScraperTest? Is that the name of a file we are downloading?

**Comment by whimboo** [comment]
`self.wdir` will automatically be available if you inherit the test case class from mhttpd.MozHttpdBaseTest. So you can just use it as in BaseScraperTest:

https://github.com/mozilla/mozdownload/blob/master/tests/base_scraper/test_base_scraper.py#L35

urljoin() is indeed used to specify the url to a locally hosted test file. You can find it here: https://github.com/mozilla/mozdownload/blob/master/tests/data/download_test.txt

So the code for the direct scraper test can mostly look totally the same in terms of navigating to the URL as for the base scraper test.

**Comment by jasonwist** [comment]
I still want to finish it. Just prepping for a big job interview next week.

**Comment by whimboo** [comment]
PR #312 has been merged to master.
