### ISSUE TITLE
Refactor docstrings which don't confirm PEP 257

### ISSUE THREAD

**Issue by kossy** [mozilla/mozdownload#217]
I noticed that some of the docstrings are not formatted properly.

For example:
```python
 def get_build_info(self):
        "Defines additional build information"
```

The docstrings should be triple double-quoted I think.

For example:
```python
 def get_build_info(self):
        """Defines additional build information"""
```
 I have only noticed this with the get_build_info functions of the scrapers in scraper.py but there may be more instances of this.

**Comment by whimboo** [comment]
This issue is still valid. PR #219 was closed because @Ayrx was not able to continue on the patch. @delta-nry if you want to take it, please feel free.

**Comment by whimboo** [comment]
I did a clean-up via issue #363. So no other warnings should remain.
