### ISSUE TITLE
Add batch for coveralls (test coverage indication)

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozdownload#223]
As seen lately on https://github.com/mozilla/kuma-private, the test coverage indication sounds pretty interesting. It's something we might also want to have for mozdownload. As it looks like they are using the [coveralls-python](https://github.com/coagulant/coveralls-python) package for that purpose.

**Comment by m-agboola** [comment]
Hi @whimboo , I would love to work on this under your guidance

**Comment by whimboo** [comment]
Oh, looks like this issue slipped through when we implemented coveralls a long time ago. You can see the current status here: https://coveralls.io/github/mozilla/mozdownload.

It means we don't need this issue anymore. In your case you can search for a different issue you would like to work on, or if you are interested in improving the test coverage, I could assist you to improve it so we may reach 100% coverage. What do you think @m-agboola?

**Comment by whimboo** [comment]
Marking as dupe of issue #396.

**Comment by m-agboola** [comment]
Thanks @whimboo , I would like to give it a try with your assistance. How do i start?

**Comment by whimboo** [comment]
As I mentioned in my 2nd last comment this issue has already been implemented. So no more work is necessary here.
