### ISSUE TITLE
Manual thunderbird tinderbox test_case is wrong

### ISSUE THREAD

**Issue by Nebelhom** [mozilla/mozdownload#238]
I just noticed earlier that the following manual test case in `test_cases.md` is wrong

`mozdownload -a thunderbird -t tinderbox -p linux --branch=mozilla-central --extension=txt`

It should be `--branch=comm-central`

Unless we are implementing this test_case any time soon, I would say this is a great first patch for a newcomer.

**Comment by whimboo** [comment]
Agreed. Marking as a mentored issue then.

**Comment by andreheringer** [comment]
I maybe be that newcomer Nebelhom is referring to. If this issue still needs attention.

**Comment by whimboo** [comment]
Oh, this was actually done via PR #402. Looks like we simply forgot to mark this issue as closed.

@andreheringer if you are still interested to help let me know and we can certainly find another spot to get you started.

**Comment by andreheringer** [comment]
@whimboo oh ok. Sure I would love to help, have 2 years of experience working in python but never contribute to open source. Yet I hope to be helpful.

**Comment by whimboo** [comment]
@andreheringer this is great. Would you mind having a look at issue #550 which just needs some tests to be disabled? It's an easy fix, and will help you to get into the project, and how to run the tests. Thanks!
