### ISSUE TITLE
Cannot download win64 bit builds of Firefox anymore

### ISSUE THREAD

**Issue by andreeamatei** [mozilla/mozdownload#243]
Our testruns failed today on win64 nodes, not being able to find today's build.
This command will show the error:
mozdownload --type=daily --branch=mozilla-central --platform=win64 --locale=en-US --build-id=20150205030205
While 32bit works.

07:13:54 [mozilla-central_functional] $ cmd.exe /C '"mozmill-env-%ENV_PLATFORM%\run mozdownload --type=%BUILD_TYPE% --branch=mozilla-central --platform=%PLATFORM% --locale=%LOCALE% --build-id=%BUILD_ID% --date=%DATE% --retry-attempts=10 --retry-delay=30 --directory=builds && exit %%ERRORLEVEL%%"'
07:13:55   INFO | Retrieving list of builds from https://ftp.mozilla.org/pub/mozilla.org/firefox/nightly/2015/02
07:13:55   WARNING | Build not found: 'Folder for builds on 2015-02-05-03-02-05 has not been found: https://ftp.mozilla.org/pub/mozilla.org/firefox/nightly/2015/02'
07:13:55   INFO    | Will retry in 30.0 seconds...

Related to bug https://bugzilla.mozilla.org/show_bug.cgi?id=1128953

**Comment by whimboo** [comment]
I will work on that. Updating the tests take a bit more time here, so a PR should be around tomorrow. I will temporarily disable testing win64 builds in mozmill-ci production.

**Comment by whimboo** [comment]
PR #248 got merged.
