### ISSUE TITLE
Change name of is_build_dir - title misleading 

### ISSUE THREAD

**Issue by Nebelhom** [mozilla/mozdownload#245]
As discussed during PR #242 (fixing issue #143) the method `is_build_dir` does not return a Boolean. As a consequence it is a misleading title.

We should change the name of the method to something more fitting.

This issue depends on #143 being fixed first so that we do not have to fix it twice.

**Comment by Nebelhom** [comment]
@whimboo 

This issue is a good first patch, I think. All it needs, is changing the function name to something that does not suggest a boolean as a result.

**Comment by Nebelhom** [comment]
@whimboo 

I have seen that by now, the function `is_buid_dir` does in fact return `True`or `False`.

https://github.com/mozilla/mozdownload/blob/master/mozdownload/scraper.py#l844

Unless you disagree, I think we can close this issue...

**Comment by whimboo** [comment]
Yes, that looks fine to me. No action to perform here.
