### ISSUE TITLE
Default branch for Thunderbird should be comm-central and not mozilla-central

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozdownload#247]
Trying to download the latest nightly of Thunderbird fails because mozdownload assume mozilla-central:

> $ mozdownload -t daily -a thunderbird
>   INFO | Retrieving the build status file from https://ftp.mozilla.org/pub/mozilla.org/thunderbird/nightly/latest-mozilla-central/

We might need a new mapping which specified the default branch for each application separately.

**Comment by son-vyas** [comment]
Hi everyone, Can I give it a try?

**Comment by son-vyas** [comment]
Thanks. I will let you know as it is ready

**Comment by andreheringer** [comment]
So, as instructed I'll be taking over this issue.

**Comment by whimboo** [comment]
Thanks a lot! Lets me know if you have questions.
