### ISSUE TITLE
Change source of builds from FTP to CDN

### ISSUE THREAD

**Issue by Nebelhom** [mozilla/mozdownload#252]
Looks like there is a source of our builds a bit closer to home

The CDN servers have all our builds in it, as well, and they appear to be faster. Check it out on http://download.cdn.mozilla.net/pub/

Maybe we can try to navigate to those first and if it does not work fall back as a safety to the ftp servers.

**Comment by whimboo** [comment]
@nthomas-mozilla, we have heard rumors that CDN might go away in the future in favor of S3. Would it hurt if we temporarily at least make use of CDN until that happens? We would get some nice speed enhancements that way at least here in Europe.

**Comment by nthomas-mozilla** [comment]
It's fine to use the CDN, and don't worry about how ftp.m.o may change in future (deal with it then!).

Out of curiosity though, do you think it'll help a lot ? Not sure how it will if cache hits are unlikely, as the CDN still needs to talk to ftp.m.o to get a copy. eg I used a shell server in Germany and requested a random nightly directly, and got 5MB/s retrieving 46M, ie 9.1s. Repeating that now that the cache is hot on ftp.m.o gave 7.0 and 12.0s transfers. Using the CDN and a different file took 11.0, 4.6, and 4.7s. ie slightly slower at first but faster on repeated requests.

See also https://bugzilla.mozilla.org/show_bug.cgi?id=1113072

**Comment by whimboo** [comment]
Thanks @nthomas-mozilla for the reply!

Mostly I expect improvements for releases here. I have had a couple of situations in the past months when I tried to download such a build during a release day or so. The download rates are very low. But also on each and every day I can see large drops in the throughput with ftp.m.o in the afternoon my time, which is when US folks are waking up. Download rates of about 700kB/s are usual then.

IMHO we should switch to CDN and we can re-evaluate later if other options exist.

**Comment by whimboo** [comment]
Removing from 1.14 milestone given that we most likely have to wontfix this request. See PR #260.

**Comment by whimboo** [comment]
See PR #260 for the reason why we wontfixed that issue.
