### ISSUE TITLE
DailyScraper: Limit checks for non-empty build dirs

### ISSUE THREAD

**Issue by Nebelhom** [mozilla/mozdownload#255]
We should implement the same change in calling `is_build_dir` for the `DailyScraper` as we have done for `TinderboxScraper` in PR #254 .

**Comment by whimboo** [comment]
@nebelhom, would you have time for that? I wonder how important it is for 1.14, and if we could post-pone it for 1.15.

**Comment by whimboo** [comment]
We will postpone this fix to the next release. It doesn't look critical due to a much lower number of builds in the builds folder.

**Comment by whimboo** [comment]
@Nebelhom would you be able to fix that issue for the 1.15 release? If not I think we should postpone this issue to a future milestone or remove the milestone information completely.

**Comment by Nebelhom** [comment]
@whimboo 

I'm sorry, I totally overlooked this issue :/ Do we have a planned due date for 1.15?

I will be able to look at it this weekend. Will that suffice?

**Comment by whimboo** [comment]
Yes, that would totally be enough.

**Comment by whimboo** [comment]
PR #283 got merged.
