### ISSUE TITLE
Test: Correct Choice of Scraper

### ISSUE THREAD

**Issue by Nebelhom** [mozilla/mozdownload#257]
This are tests that still needs automation and are inter-related.

```
mozdownload -t release -p win32 -v latest
mozdownload -t candidate -p win32 -v 21.0
mozdownload -t daily -p win32
mozdownload -t tinderbox -p win32
```

**Comment by Nebelhom** [comment]
@whimboo @davehunt and anyone else knowledgeable in writing tests.

I have been pondering over this particular implementation for quite some time, but cannot find a good solution of it.

Essentially, when implementing this, we need to call the `cli()` function and then check if we have the correct scraper. Anything else, in my eyes, is not really testing but writing a function that gives you a pre-determined answer at point of writing.

At the moment, `cli()` is a closed sequence, that when called, checks the arguments passed on, chooses a scraper accordingly and then starts downloading a build if possible.

The only way I have found to create a decent test for it, is to break up `cli()`into two parts. The "matching-the-arguments" part and the "downloading" part (Passing arguments in_between the two)

Q1: Can anyone think of a better, more elegant or simpler way?

Q2: Is it actually feasible to break up the `cli()` function, to allow for more effective testing? We don't have to implement test-driven development, but we are going in the direction of having tests in place for each function, anyways...

Looking forward to a constructive discussion :)

**Comment by whimboo** [comment]
Personally I would say that we have perfect coverage for that already. I don't think we have to invest our time for checking if the correct scraper has been used. Reason is that if a wrong scraper would have been chosen, other existing tests would fail. There might only be a small gap here between release and candidate scrapers. But even there we have to `buildX` part we expect for the latter.

So lets drop it?

**Comment by Nebelhom** [comment]
@whimboo 

I think you forget that we never test if the scraper chooses the right type. For our tests, we directly invoke the correct type for those tests. Check the following link:

https://github.com/mozilla/mozdownload/blob/master/tests/daily_scraper/test_daily_scraper.py#l318

So as you can see, for all the tests that we are doing, we directly create an instance of `DailyScraper`, rather than letting the script come to its own conclusion that we need the DailyScraper.

I agree that we do not want to do it, if we only check for the correct choice of scraper, because we would only check for typos in the `BUILD-TYPE` block ( https://github.com/mozilla/mozdownload/blob/master/tests/daily_scraper/test_daily_scraper.py#l318 ). However, it might be worthwhile to write tests for all flags. Typos are easily done and they are hard to spot once they are in.

**Comment by whimboo** [comment]
Oh! I see now. You are right. Personally I wouldn't put too much work in it. So what if we simply invoke mozdownload via mozprocess and a CLI command? We know the expected filename, and could compare it. It's not perfect but would at least check the right choice of the scraper. What do you think?
