### ISSUE TITLE
 mozdownload cannot load tinderbox zip builds for Windows

### ISSUE THREAD

**Issue by sydvicious** [mozilla/mozdownload#258]
mozdownload --type=tinderbox --platform=win32 --extension=zip --branch=mozilla-beta

The regular expression at line 760 ends up looking for firefox*.en-US.win32.installer.zip, which it won't find.

        regex_base_name = r'^%(APP)s-.*\.%(LOCALE)s\.%(PLATFORM)s'
        regex_suffix = {'linux': r'.*\.%(EXT)s$',
                        'linux64': r'.*\.%(EXT)s$',
                        'mac': r'.*\.%(EXT)s$',
                        'mac64': r'.*\.%(EXT)s$',
                        'win32': r'.*(\.installer%(STUB)s)\.%(EXT)s$',
                        'win64': r'.*(\.installer%(STUB)s)\.%(EXT)s$'}

**Comment by whimboo** [comment]
We want this fix in the next release 1.14.

**Comment by sydvicious** [comment]
Supercded by #264
