### ISSUE TITLE
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'

### ISSUE THREAD

**Issue by qas612820704** [mozilla/mozdownload#268]
After I execute
$ sudo ./step.py install
then the error occour,
what should I do?

**Comment by Nebelhom** [comment]
Hi @qas612820704 

This is the first time that I have come across this issue, so I would have to figure this out myself, as well, first.

@whimboo @davehunt Have you seen this problem before?

**Comment by whimboo** [comment]
What is step.py? What you want to do is to run 'sudo pip install mozdownload' or if you want to have a developer version 'sudo python setup.py develop'.

**Comment by whimboo** [comment]
If its still happening with those commands, please also paste the whole traceback of the error you are seeing. I strongly believe its a networking issue on your side.

**Comment by whimboo** [comment]
I strongly believe this is/was a problem with the installation steps. Nothing on our side. Given the lack of feedback I'm closing this issue now.

**Comment by qas612820704** [comment]
I'm so sorry ~ I don't focus this for a lot of day after I remain this comment 
This is the full information after I execute 'sudo pip install mozdownload'
---
  Requirement already satisfied (use --upgrade to upgrade): mozdownload in /usr/local/lib/python2.7/dist-packages/mozdownload-1.14-py2.7.egg
Collecting mozinfo>=0.7 (from mozdownload)
  Downloading mozinfo-0.7.tar.gz
Collecting mozlog>=1.3 (from mozdownload)
  Downloading mozlog-2.10.tar.gz
Collecting progressbar==2.2 (from mozdownload)
  Downloading progressbar-2.2.tar.gz
Collecting requests==1.2.2 (from mozdownload)
  Downloading requests-1.2.2.tar.gz (348kB)
    100% |################################| 352kB 809kB/s 
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-luZbMS/requests/setup.py", line 6, in <module>
        import requests
      File "requests/__init__.py", line 53, in <module>
        from requests.packages.urllib3.contrib import pyopenssl
      File "requests/packages/urllib3/contrib/pyopenssl.py", line 42, in <module>
        ssl.PROTOCOL_SSLv3: OpenSSL.SSL.SSLv3_METHOD,
    AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
    
      File "<string>", line 20, in <module>
    
      File "/tmp/pip-build-luZbMS/requests/setup.py", line 6, in <module>
    
        import requests
    
      File "requests/__init__.py", line 53, in <module>
    
        from requests.packages.urllib3.contrib import pyopenssl
    
      File "requests/packages/urllib3/contrib/pyopenssl.py", line 42, in <module>
    
        ssl.PROTOCOL_SSLv3: OpenSSL.SSL.SSLv3_METHOD,
    
    AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-luZbMS/requests

**Comment by whimboo** [comment]
This looks to be a problem in the requests package. I assume you get the same failure when you run `sudo pip install --upgrade requests==1.2.2`? If that is the case what about `sudo pip install --upgrade requests`?

**Comment by qas612820704** [comment]
Yes~ I get the same failure when run `sudo pip install --upgrade requests==1.2.2`
but even through I run `sudo pip install --upgrade requests`,
the problem still not solve

---
```
$ sudo pip install --upgrade requests
```
Requirement already up-to-date: requests in /usr/local/lib/python2.7/dist-packages

---
```
$sudo pip install mozdownload
```
Requirement already satisfied (use --upgrade to upgrade): mozdownload in /usr/local/lib/python2.7/dist-packages/mozdownload-1.14-py2.7.egg
Collecting mozinfo>=0.7 (from mozdownload)
  Using cached mozinfo-0.7.tar.gz
Collecting mozlog>=1.3 (from mozdownload)
  Using cached mozlog-2.10.tar.gz
Collecting progressbar==2.2 (from mozdownload)
  Using cached progressbar-2.2.tar.gz
Collecting requests==1.2.2 (from mozdownload)
  Using cached requests-1.2.2.tar.gz
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-Okfb6h/requests/setup.py", line 6, in <module>
        import requests
      File "requests/__init__.py", line 53, in <module>
        from requests.packages.urllib3.contrib import pyopenssl
      File "requests/packages/urllib3/contrib/pyopenssl.py", line 42, in <module>
        ssl.PROTOCOL_SSLv3: OpenSSL.SSL.SSLv3_METHOD,
    AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
    
      File "<string>", line 20, in <module>
    
      File "/tmp/pip-build-Okfb6h/requests/setup.py", line 6, in <module>
    
        import requests
    
      File "requests/__init__.py", line 53, in <module>
    
        from requests.packages.urllib3.contrib import pyopenssl
    
      File "requests/packages/urllib3/contrib/pyopenssl.py", line 42, in <module>
    
        ssl.PROTOCOL_SSLv3: OpenSSL.SSL.SSLv3_METHOD,
    
    AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-Okfb6h/requests

**Comment by parkouss** [comment]
@qas612820704 maybe this is related if you are running under debian:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=770172
http://stackoverflow.com/questions/28987891/patch-pyopenssl-for-sslv3-issue

**Comment by qas612820704** [comment]
After run `$ sudo pip uninstall pyopenssl`
and retry `$ sudo pip install mozdownload`
It's work!
Thanks you so much! :)

**Comment by parkouss** [comment]
:)

**Comment by whimboo** [comment]
Good to know that! Thanks @parkouss for helping out! At least I have now seen that we should upgrade our requests dependency to the 2.x branch. We are still so far behind! :( I will file a new issue.
