### ISSUE TITLE
We can't determine the latest beta and release candidate

### ISSUE THREAD

**Issue by armenzg** [mozilla/mozdownload#273]
https://ftp.mozilla.org/pub/mozilla.org/firefox/candidates/latest-beta-candidates does not exist anymore. Creating the symlink is probably not automated anymore as part of the release process. [1]

There are various options we have in here:
* parse the candidates page and find the most recent *beta* folder "37.0b7-candidates"
* mozci allows you to navigate through all of the scheduling data from the releng systems
** I just inspected the buildjson file of 2015-03-20 and contains all the data we would need [2]
* We can also determine the latest version from the releng configs [3]

I suggest we go for option 2 since mozci will become a long term project that allows us to inspect data about any jobs on the Releng CI.

[1]
armenzg@armenzg-thinkpad:~/repos/mozdownload$ mozdownload -t candidate -v latest-beta
https://ftp.mozilla.org/pub/mozilla.org/firefox
HEY HEY
  INFO | Retrieving list of candidate builds from https://ftp.mozilla.org/pub/mozilla.org/firefox/candidates/latest-beta-candidates/
Traceback (most recent call last):
  File "/usr/local/bin/mozdownload", line 9, in <module>
    load_entry_point('mozdownload==1.14', 'console_scripts', 'mozdownload')()
  File "/home/armenzg/repos/mozdownload/mozdownload/scraper.py", line 1255, in cli
    build = BUILD_TYPES[options.type](**kwargs)
  File "/home/armenzg/repos/mozdownload/mozdownload/scraper.py", line 642, in __init__
    Scraper.__init__(self, *args, **kwargs)
  File "/home/armenzg/repos/mozdownload/mozdownload/scraper.py", line 160, in __init__
    raise NotFoundError(message, e.response.url)
mozdownload.scraper.NotFoundError: Specified build has not been found: https://ftp.mozilla.org/pub/mozilla.org/firefox/candidates/latest-beta-candidates/

[2] http://builddata.pub.build.mozilla.org/builddata/buildjson/builds-2015-03-20.js.gz
        "packageUrl": "http://stage.mozilla.org/pub/mozilla.org/firefox/nightly/37.0b7-candidates/build1/win32/en-US/firefox-37.0b7.zip",
[3] http://mxr.mozilla.org/build/source/buildbot-configs/mozilla/release-firefox-mozilla-beta.py#24

**Comment by sydvicious** [comment]
I need to test with a binary and a tests.zip file. I generally need to .txt file to get the build number without having to unpack the binary archive (esp. the mac .dmg file). With nightly and aurora, mozdownload does all of this with ease. However, this is very difficult in beta and release.

You can use tinderbox builds, but the files do not change names every build like nightly and aurora do. mozdownload could encode the build somehow, but it does not currently.

Even if -t candidate -v latest-beta somehow worked, there would still be a need to track down the buildid and the .tests.zip file that corresponded to that build. The same is true for release.

**Comment by whimboo** [comment]
I do not see a reason why we should bind mozdownload that close to mozci. It's an independent project and should not rely on releng specific behavior. It's sad that there is no latest beta or latest release link but AFAIR we never had that.

@sydvicious, I mentioned to you a couple of times that you are better to use Mozilla Pulse to listen for notifications of candidate builds. This is what we do with Mozmill CI for a couple of years now and which works like a charm. I would propose that we have a chat and talk about it, instead of bringing up the same questions over and over again. Does that sound okish for you?

**Comment by sydvicious** [comment]
I agree that using pulse is the long-term correct solution here. It's just a shame that independent of automation, one can't reliably get auxiliary products from beta releases using mozdownload.

**Comment by whimboo** [comment]
This is fixed with my patch on issue #356.
