### ISSUE TITLE
Download builds from S3 instead from archive.mozilla.org

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozdownload#278]
[Bug 1136822](https://bugzilla.mozilla.org/show_bug.cgi?id=1136822) has been filed for tracking this work in regards of other bugs in Bugzilla. But the real implementation work will happen here.

CC'ing @jonallengriffin, @AutomatedTester

**Comment by parkouss** [comment]
adding myself in the CC list.

**Comment by whimboo** [comment]
This was already fixed a while ago for release 1.19.
