### ISSUE TITLE
Enhance documentation for developer related activities

### ISSUE THREAD

**Issue by juj** [mozilla/mozdownload#307]
Hey, I was setting up mozdownload on Windows, and when learning for the first time, I was scratching my head on the following for a moment:

1. I did not know what to do with the git repo after cloning. There was no mozdownload script included, and readme did not have Windows instructions. Running "python setup.py" gave this:

		C:\code\mozdownload>python setup.py
		usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
		   or: setup.py --help [cmd1 cmd2 ...]
		   or: setup.py --help-commands
		   or: setup.py cmd --help

		error: no commands supplied

and I did not know how to proceed.

2. On the web page https://pypi.python.org/pypi/mozdownload , the first two links are broken, so I wondered if the package had gone stale altogether over time and not used anymore.

3. Then I just randomly tried "pip install mozdownload", following the instructions that exist for installing the mozregression tool for Windows here: http://mozilla.github.io/mozregression/install.html and that worked! It would be good to document similar "Installing on Windows"

4. Running the first example command on Windows gives the following error:

		C:\code\mozdownload>mozdownload --version=latest
		Traceback (most recent call last):
		  File "C:\Python27\Scripts\mozdownload-script.py", line 9, in <module>
		    load_entry_point('mozdownload==1.17', 'console_scripts', 'mozdownload')()
		  File "C:\Python27\lib\site-packages\mozdownload\scraper.py", line 1244, in cli
		    build.download()
		  File "C:\Python27\lib\site-packages\mozdownload\scraper.py", line 275, in download
		    if os.path.isfile(os.path.abspath(self.target)):
		  File "C:\Python27\lib\site-packages\mozdownload\scraper.py", line 237, in target
		    self.build_filename(self.binary))
		  File "C:\Python27\lib\site-packages\mozdownload\scraper.py", line 190, in binary
		    raise errors.NotFoundError(message, self.path)
		mozdownload.errors.NotFoundError: Specified build has not been found: https://archive.mozilla.org/pub/mozilla.org/firefox/releases/latest/win64/en-US

which I could not understand. Whimboo explained on IRC that it's because it attempts to find 64-bit release builds for Windows, which do not exist.

Downloading the mozilla-central builds is what I was after, and eventually I was able to get it working. Thanks for the great tool! Just wanted to point out these observations to ease the Windows first run experience.

**Comment by whimboo** [comment]
Yeah. We certainly need some developer docs layed out for this repository. I will see that I find time this week to do that.

**Comment by whimboo** [comment]
PR #308 has been merged and fixes all the mentioned issues from comment 0.
