### ISSUE TITLE
Don't retrieve directory listing if timestamp is provided for Tinderbox builds

### ISSUE THREAD

**Issue by EricRahm** [mozilla/mozdownload#313]
Retrieving a full directory listing [1] is not necessary if the timestamp is already known [2].

This is relevant for AreWeSlimYet where we often retrieve all builds for a given date range.

[1] https://github.com/mozilla/mozdownload/blob/master/mozdownload/scraper.py#L875
[2] https://github.com/mozilla/mozdownload/blob/master/mozdownload/scraper.py#L879-L883

**Comment by whimboo** [comment]
Hard to say right now, given that the code references were put against master and not a specific revision. As the code has been changed over the last three years, those references aren't valid anymore.

@EricRahm could you please have a look again?

**Comment by EricRahm** [comment]
@whimboo The original links appear to be [1,2] referring to `get_build_info_for_index`. I think this maps to [3,4]. Unfortunately I don't 100% recall what needed to change. At this point AWSY no longer uses mozdownload.

[1] https://github.com/mozilla/mozdownload/blob/94e473c120dbb62d2a7d63975dcedd8116e52dab/mozdownload/scraper.py#L875
[2] https://github.com/mozilla/mozdownload/blob/94e473c120dbb62d2a7d63975dcedd8116e52dab/mozdownload/scraper.py#L879-L883
[3] https://github.com/mozilla/mozdownload/blob/b412d28a2ec8e59cedcc40804e9f86a9f6e0993d/mozdownload/scraper.py#L905
[4] https://github.com/mozilla/mozdownload/blob/b412d28a2ec8e59cedcc40804e9f86a9f6e0993d/mozdownload/scraper.py#L908-L912

**Comment by whimboo** [comment]
Ok, now I see. So this is actually the following code on master:
https://github.com/mozilla/mozdownload/blob/9ec6fc5/mozdownload/scraper.py#L904-L916

So we indeed could move the if block for the timestamp before retrieving the directory listing. Then we only have to retrieve the list of directories if no timestamp is given.

@wardt7 do you still have interest to work on this issue? Sorry that it took a bit to clarify the state but I was away nearly all of December.

**Comment by sbeesm** [comment]
Hi! Is this issue still open? Can I work on this one?

**Comment by sbeesm** [comment]
So we just have to move the `_create_directory_parser` [1] in an if block that would only run if no timestamp is provided, right? I hope I'm not missing something.

[1]  https://github.com/mozilla/mozdownload/blob/9ec6fc5/mozdownload/scraper.py#L904-L906

**Comment by whimboo** [comment]
Something like that yes. I would suggest to try this out, and verify your changes with existing tests and also by using mozdownload yourself via the command line. Maybe we don't have a test yet, which checks for an invalid timestamp.

**Comment by sbeesm** [comment]
I'm not able to run mozdownload via the git bash command line. It shows an error:
```
$ python mozdownload --help
C:\Anaconda3\python.exe: can't find '__main__' module in 'mozdownload'
```
and

```
>>> from mozdownload import FactoryScraper
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "F:\COMPILED\Git\mozdownload\mozdownload\__init__.py", line 7, in <module>
    from mozdownload import cli
  File "F:\COMPILED\Git\mozdownload\mozdownload\cli.py", line 16, in <module>
    from mozdownload import factory, scraper
  File "F:\COMPILED\Git\mozdownload\mozdownload\factory.py", line 9, in <module>
    from mozdownload import scraper
  File "F:\COMPILED\Git\mozdownload\mozdownload\scraper.py", line 15, in <module>
    from urlparse import urlparse
ModuleNotFoundError: No module named 'urlparse'
```

After cloning the repository, this command runs successfully: `python setup.py develop` but mozdownload doesn't work.
Can you please tell me how to fix this.

**Comment by whimboo** [comment]
@sbeesm it looks like you are using Python 3 but sadly mozdownload is not compatible to it yet. See issue #415. For now you will have to use Python2.7. But feel free to also have a look at the other issue. Help is welcome to make us compatible to both 2.7 and 3.x.

**Comment by gkprasanth** [comment]
@EricRahm 
Hi I am Krishna,
I have basic knowledge of python. Do you think I can work on this with the basic python knowledge and no experience in open source?

**Comment by EricRahm** [comment]
@gkprasanth Thanks for offering to help! I'm no longer active with the project, unfortunately I'm not sure what the status is of active development. @whimboo Are you still looking for volunteers here?

**Comment by gkprasanth** [comment]
@EricRahm 
It's okay.
But if you could help me contribute to Mozilla by  advising, I mean giving me information on projects, such as prerequisites, the level of coding expertise needed, etc.
I would really like to contribute to open source, but I'm not sure exactly how to do it.

**Comment by whimboo** [comment]
I would greatly appreciate help on this project. But this issue might not be the best one to get started. @gkprasanth what do you think about issue #621? Thanks a lot!
