### ISSUE TITLE
Failure: 'NoneType' object has no attribute 'status_code'

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozdownload#314]
This happened when our mozmill-ci job tried to download the Nighlty build with the build-id 20150831030209. It cannot be replicated anymore given that the build exists now. Maybe it happens when the build folder exists but the build for the given platform is not available.

Failure:
> 12:17:10     Scraper.__init__(self, *args, **kwargs)
12:17:10   File "/Users/mozauto/jenkins/workspace/mozilla-central_functional/venv/lib/python2.7/site-packages/mozdownload/scraper.py", line 143, in __init__
12:17:10     e.response.status_code == 404:
12:17:10 AttributeError: 'NoneType' object has no attribute 'status_code'

Line of code:
https://github.com/mozilla/mozdownload/blob/master/mozdownload/scraper.py#L142

**Comment by EricRahm** [comment]
@whimboo  I saw this recently in AWSY. Mozilla having infra issues at the time, so maybe it was the result of a timeout? FWIW I generally get BuildNotFoundError when the build is not found, so I don't think that's it.

**Comment by parkouss** [comment]
@EricRahm Do you have the stack trace of the exception by any chance ? Since the code has changed since the bug was reported, that can help.

**Comment by EricRahm** [comment]
@parkouss Unfortunately I just have a log of the exception, not the stack. It's pretty clear it's coming from scraper though as that's the only place that checks `status_code` [1].

[1] https://github.com/mozilla/mozdownload/blob/042f08811faea146553b0741124bef4d50741662/mozdownload/scraper.py#L139

**Comment by whimboo** [comment]
PR #347 has been merged. Thank you @EricRahm for the investigation and fix!
