### ISSUE TITLE
Use a shared HTTP/HTTPS session() for retrieving data

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozdownload#328]
As of now we seem to make individual connections to the remote host for querying every tiny information and finally downloading the build. It would be better to share those connections via a session (http://docs.python-requests.org/en/latest/user/advanced/#session-objects). It can result in a more or less good speed improvement.

**Comment by whimboo** [comment]
Downloading an Aurora build shows the following connections being created:

    15:49:38     INFO - Retrieving list of builds from https://archive.mozilla.org/pub/mozilla.org/firefox/nightly/2015/09
    15:49:38     INFO - Starting new HTTPS connection (1): archive.mozilla.org
    15:49:39     INFO - Starting new HTTP connection (1): archive.mozilla.org
    15:49:40     INFO - Starting new HTTPS connection (1): archive.mozilla.org
    15:49:42     INFO - Starting new HTTP connection (1): archive.mozilla.org
    15:49:43     INFO - Found 1 build: 2015-09-14-00-40-20-mozilla-aurora
    15:49:43     INFO - Selected build: 2015-09-14-00-40-20-mozilla-aurora
    15:49:43     INFO - Starting new HTTPS connection (1): archive.mozilla.org
    15:49:45     INFO - Starting new HTTP connection (1): archive.mozilla.org

**Comment by whimboo** [comment]
It will also help us with the authentication given that we only have to set the credentials when the session gets created.

**Comment by whimboo** [comment]
So this can be done by adding the following line to the scraper.py module:

> logging.getLogger("requests").setLevel(logging.DEBUG)

It will enable the maximum amount of logging output. Here how it looks like when we download the latest Nightly build:

> INFO | Retrieving the build status file from https://archive.mozilla.org/pub/mozilla.org/firefox/nightly/latest-mozilla-central/
 INFO | Starting new HTTPS connection (1): archive.mozilla.org
 DEBUG | "GET /pub/mozilla.org/firefox/nightly/latest-mozilla-central/ HTTP/1.1" 200 None
 INFO | Starting new HTTPS connection (1): archive.mozilla.org
 DEBUG | "GET /pub/mozilla.org/firefox/nightly/latest-mozilla-central/firefox-43.0a1.en-US.linux-x86_64.txt HTTP/1.1" 200 99
 INFO | Retrieving list of builds from https://archive.mozilla.org/pub/mozilla.org/firefox/nightly/2015/09
 INFO | Starting new HTTPS connection (1): archive.mozilla.org
 DEBUG | "GET /pub/mozilla.org/firefox/nightly/2015/09 HTTP/1.1" 301 275
 INFO | Starting new HTTP connection (1): archive.mozilla.org
 DEBUG | "GET /pub/mozilla.org/firefox/nightly/2015/09/ HTTP/1.1" 200 None
 INFO | Starting new HTTPS connection (1): archive.mozilla.org
 DEBUG | "GET /pub/mozilla.org/firefox/nightly/2015/09/2015-09-15-03-02-32-mozilla-central HTTP/1.1" 301 311
 INFO | Starting new HTTP connection (1): archive.mozilla.org
 DEBUG | "GET /pub/mozilla.org/firefox/nightly/2015/09/2015-09-15-03-02-32-mozilla-central/ HTTP/1.1" 200 None
 INFO | Found 1 build: 2015-09-15-03-02-32-mozilla-central
 INFO | Selected build: 2015-09-15-03-02-32-mozilla-central
 INFO | Starting new HTTPS connection (1): archive.mozilla.org
 DEBUG | "GET /pub/mozilla.org/firefox/nightly/2015/09/2015-09-15-03-02-32-mozilla-central HTTP/1.1" 301 311
 INFO | Starting new HTTP connection (1): archive.mozilla.org
 DEBUG | "GET /pub/mozilla.org/firefox/nightly/2015/09/2015-09-15-03-02-32-mozilla-central/ HTTP/1.1" 200 None
 INFO | Downloading from: https://archive.mozilla.org/pub/mozilla.org/firefox/nightly/2015/09/2015-09-15-03-02-32-mozilla-central/firefox-43.0a1.en-US.linux-x86_64.tar.bz2
 INFO | Saving as: /mozilla/code/mozdownload/2015-09-15-03-02-32-mozilla-central-firefox-43.0a1.en-US.linux-x86_64.tar.bz2
 INFO | Starting new HTTPS connection (1): archive.mozilla.org
 DEBUG | "GET /pub/mozilla.org/firefox/nightly/2015/09/2015-09-15-03-02-32-mozilla-central/firefox-43.0a1.en-US.linux-x86_64.tar.bz2 HTTP/1.1" 200 58259771

**Comment by parkouss** [comment]
With requests logging enabled, output looks like:
```
mozdownload --type=daily --branch=mozilla-aurora --platform=win32                                                                                                 master * ] 12:22 
 INFO | Retrieving the build status file from https://archive.mozilla.org/pub/firefox/nightly/latest-mozilla-aurora/
 INFO | Starting new HTTPS connection (1): archive.mozilla.org
 DEBUG | "GET /pub/firefox/nightly/latest-mozilla-aurora/ HTTP/1.1" 200 None
 DEBUG | "GET /pub/firefox/nightly/latest-mozilla-aurora/firefox-44.0a2.en-US.win32.txt HTTP/1.1" 200 107
 INFO | Retrieving list of builds from https://archive.mozilla.org/pub/firefox/nightly/2015/11/
 DEBUG | "GET /pub/firefox/nightly/2015/11/ HTTP/1.1" 200 10132
 DEBUG | "GET /pub/firefox/nightly/2015/11/2015-11-08-00-40-59-mozilla-aurora/ HTTP/1.1" 200 None
 INFO | Found 1 build: 2015-11-08-00-40-59-mozilla-aurora
 INFO | Selected build: 2015-11-08-00-40-59-mozilla-aurora
 DEBUG | "GET /pub/firefox/nightly/2015/11/2015-11-08-00-40-59-mozilla-aurora/ HTTP/1.1" 200 None
 INFO | Downloading from: https://archive.mozilla.org/pub/firefox/nightly/2015/11/2015-11-08-00-40-59-mozilla-aurora/firefox-44.0a2.en-US.win32.installer.exe
 INFO | Saving as: /home/jp/dev/mozdownload/2015-11-08-00-40-59-mozilla-aurora-firefox-44.0a2.en-US.win32.installer.exe
 DEBUG | "GET /pub/firefox/nightly/2015/11/2015-11-08-00-40-59-mozilla-aurora/firefox-44.0a2.en-US.win32.installer.exe HTTP/1.1" 200 42466616
^C1% |###################                                                                                                                                                               | ETA:  00:00:30   1.24 M/s
Download interrupted by the user
```

**Comment by whimboo** [comment]
Sweet! Looking forward to a PR from you.

**Comment by whimboo** [comment]
PR #341 got merged to master. Thanks @parkouss for working on that! I wonder about the performance win we will have here...
