### ISSUE TITLE
Add option to print final url to standard output

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozdownload#344]
It would be helpful to have an option to let mozdownload print the final url to stdout. It could be used with pipes to pass into another application or stored to disk.

**Comment by Prashant-Surya** [comment]
Can i work on this issue?

**Comment by whimboo** [comment]
@Prashant-Surya you are welcome to do so! Sorry for the late reply, but I was away a couple of days and had to work through a lot of email to finally reach this notification from github. Please let me know if you are still interested in. Thanks.

**Comment by Prashant-Surya** [comment]
@whimboo yes, I'm still interested. I'll send a pull request.

**Comment by whimboo** [comment]
PR #416 got merged.
