### ISSUE TITLE
test_optional_authentication is broken

### ISSUE THREAD

**Issue by EricRahm** [mozilla/mozdownload#348]
`test_optional_authentication` [1] attempts to use https://ci.mozilla.org, that site is down and they're planning on decommissioning it [2].

This has the unfortunate side effect of making PRs seem like they've caused test failures.

[1] https://github.com/mozilla/mozdownload/blob/master/tests/base_scraper/test_base_scraper.py#L99
[2] https://bugzilla.mozilla.org/show_bug.cgi?id=1229734

**Comment by davehunt** [comment]
In the short term you may be able to switch to https://webqa-ci.mozilla.com/ which has no plans of decommissioning.

**Comment by whimboo** [comment]
PR #349 has been merged.
