### ISSUE TITLE
Make use of tox as test runner for unit tests

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozdownload#352]
We should make use of [tox](https://testrun.org/tox/latest/) as testrunner for our unit tests. It has some nice features like automatic environment creation which would help us a lot here. Maybe we could even integrate coverage reports at the same time.

For an example see the mozharness tox configuration file:
http://mxr.mozilla.org/mozilla-central/source/testing/mozharness/tox.ini

**Comment by Motwani** [comment]
I would like to work on this Issue.

**Comment by whimboo** [comment]
That's great to hear! So I've set you as assignee for this issue. Let me know if you have problems in #ateam or #automation. Thanks!

**Comment by whimboo** [comment]
@Motwani do you already have an idea when you can get started with this issue? I would need an easy way to trigger specific tests only, which is not easily doable right now. Thanks.

**Comment by Motwani** [comment]
I have a fair idea about Tox. I'm not sure how to trigger specific tests but I could make a similar tox file using git instead of mercurial. Which versions of Git should I test with? And how can I trigger specific tests?

**Comment by whimboo** [comment]
The first step for this issue should be add tox and let it create the required virtual environment. We could then also make use of the coverage module similar to mozharness and let the tests being triggered through it.

**Comment by whimboo** [comment]
PR #358 has been merged. As we noticed coverage doesn't really work as of now. So I will file a follow-up issue now.

Aditya, thanks a lot for making this possible! I already love this new feature.
