### ISSUE TITLE
mozdownload gets SDK packages for candidate and release builds of Firefox 44.0

### ISSUE THREAD

**Issue by l-hedgehog** [mozilla/mozdownload#353]
I noticed the files were 132M instead of the normal 49M, these sdk.tar.bz2 were not there before Fx 44.0 rc build3.

 » mozdownload --build-number 3 -l en-US -p linux -t candidate -v 44.0
 INFO | Retrieving list of candidate builds from https://archive.mozilla.org/pub/mozilla.org/firefox/candidates/44.0-candidates/
 INFO | Found 3 builds: build1, build2, build3
 INFO | Selected build: build3
 INFO | Downloading from: https://archive.mozilla.org/pub/mozilla.org/firefox/candidates/44.0-candidates/build3/linux-i686/en-US/firefox-44.0.sdk.tar.bz2
 INFO | Saving as: /home/bzhao/repos/chinarepack-monitor/firefox-44.0-build3.en-US.linux.tar.bz2
100% |#####################################################################################################################| Time: 00:01:28   1.55 M/s

**Comment by whimboo** [comment]
Thanks for the report! And sorry for not seeing it earlier. So starting with Firefox 44.0 we want to ship the SDK along the releases again. That has been implemented on [bug 1233005](https://bugzilla.mozilla.org/show_bug.cgi?id=1233005). I'm not quite sure yet why we started to use the en-US folder. So I asked on the bug. Maybe we can better use a folder like `linux-i686/sdk/` for those builds.

**Comment by whimboo** [comment]
This also happens for release builds. Looks like we need a bustage release soon.

**Comment by whimboo** [comment]
I will work on that. The PR which I will create will be based on top of PR #356.

**Comment by whimboo** [comment]
PR #357 got merged. The fix will be part of the next release which will happen the next days.
