### ISSUE TITLE
Use pytest or nose as testrunner for unit tests

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozdownload#359]
PR #358 has been shown that coverage doesn't really work. This might be related to the unittest framework we make use of. Maybe we should switch away from that and better use nose or even pytest to run our tests.

https://testrun.org/tox/latest/example/pytest.html

@Motwani, as you told on the other issue you are interested to work on it?

**Comment by Motwani** [comment]
Yes , I would like to work on this issue. 

I am not sure what you meant by "switch away from unittest " ?

**Comment by whimboo** [comment]
My fault given that I also don't know about those details yet. So pytest seem to be a testrunner which supports unittest like tests. So we hopefully shouldn't have to change any of our tests.

**Comment by whimboo** [comment]
PR #394 got merged.
