### ISSUE TITLE
Add pylama call to tox config file

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozdownload#395]
Right now we are running pylama only for Travis and AppVeyor. It would be good to add this call to the tox.ini file instead so that we can also benefit from that in local testing.

@Motwani would you like to take this issue?

**Comment by Motwani** [comment]
Yep I would love to work on this :)

**Comment by whimboo** [comment]
This looks great now. I will get it merged in a moment.

**Comment by whimboo** [comment]
Merged the PR as https://github.com/mozilla/mozdownload/commit/0cbc6a183a613ee553a4a1759eae72155f1468b3.
