### ISSUE TITLE
Allow to run individual test files / folders via tox

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozdownload#398]
I would like to run a single folder with tests or a test only via tox. Therefore {posargs} can be used.

@Motwani do you want to do the small change?

**Comment by Motwani** [comment]
Calling many tests via posargs fails to call mozhttpd_base_test.py thus making it difficult to call all tests.

Any idea how to fix this along with adding {posargs} ? @whimboo

**Comment by whimboo** [comment]
Looks like the problem here is the base directory discovery. When we pass in specific tests those are all a level below the `tests` folder and the `mozhttpd_base_test.py` module. As result pytest cannot find the customized TestCase class. @davehunt would you have a suggestion for us what's best here?

**Comment by davehunt** [comment]
I would suggest asking in #pylib on IRC. I've not encountered this issue in any of my projects.

**Comment by whimboo** [comment]
Hi @Motwani. Where you able to find some time to check on the beforementioned IRC channel on a freenode server?

**Comment by whimboo** [comment]
PR #412 got this fixed. Thanks Johannes!
