### ISSUE TITLE
Mozdownload 1.21 does not find Fennec builds

### ISSUE THREAD

**Issue by juj** [mozilla/mozdownload#410]
Running `mozdownload --version=latest --type=daily --date=2016-09-25 --application=fennec -p android-api-15`

gives

    INFO | Retrieving list of builds from https://archive.mozilla.org/pub/mobile/nightly/2016/09/
    Traceback (most recent call last):
      File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "c:\python27\lib\runpy.py", line 72, in _run_code
        exec code in run_globals
      File "C:\Python27\Scripts\mozdownload.exe\__main__.py", line 9, in <module>
      File "c:\python27\lib\site-packages\mozdownload\cli.py", line 165, in cli
        build = factory.FactoryScraper(scraper_type, **kwargs)
      File "c:\python27\lib\site-packages\mozdownload\factory.py", line 125, in __init__
        scraper_types[scraper_type].__init__(self, **kwargs)
      File "c:\python27\lib\site-packages\mozdownload\scraper.py", line 344, in __init__
        Scraper.__init__(self, *args, **kwargs)
      File "c:\python27\lib\site-packages\mozdownload\scraper.py", line 133, in __init__
        self._retry_check_404(self.get_build_info)
      File "c:\python27\lib\site-packages\mozdownload\scraper.py", line 148, in _retry_check_404
        self._retry(func, **retry_kwargs)
      File "c:\python27\lib\site-packages\mozdownload\scraper.py", line 139, in _retry
        return redo.retry(func, **retry_kwargs)
      File "c:\python27\lib\site-packages\redo\__init__.py", line 152, in retry
        return action(*args, **kwargs)
      File "c:\python27\lib\site-packages\mozdownload\scraper.py", line 401, in get_build_info
        self.date, self.build_index)
      File "c:\python27\lib\site-packages\mozdownload\scraper.py", line 482, in get_build_info_for_date
        raise errors.NotFoundError(message, url)
    mozdownload.errors.NotFoundError: Folder for builds on 2016-09-25 has not been found: https://archive.mozilla.org/pub/mobile/nightly/2016/09/

However manually eyeballing the directory, there does exists [2016-09-25-03-02-26-mozilla-central-android-api-15](https://archive.mozilla.org/pub/mobile/nightly/2016/09/2016-09-25-03-02-26-mozilla-central-android-api-15/) directory, which should be the one that this command line should be looking at?

**Comment by whimboo** [comment]
The folder exists indeed but there is no multi build contained. So this should be the problem here. If you would add `--locale=en-US` it should work. Can you please verify that? Thanks.

**Comment by juj** [comment]
Thanks! Adding `--locale=en-US` does work.

It might be helpful to improve the error message here, since it says "Folder [...] not found: <url>", which makes the error message interpretable as "this URL does not exist -> <url>". Perhaps the appropriate error here would be to say that "multi-build <url-to-apk-name> does not exist for this date" or similar, if that is the actual error?

Btw, any idea why there does exist a build for locale en-US but no multilanguage build? Does the build system not create multilanguage builds sometimes? I'm maintaining a unit testing framework which tests each nightly version of Firefox on both desktop and mobile, and I think I might just want to always download the en-US locale then if that has better % chances of existing over the default multilanguage build. Does always passing `--locale=en-US` to all downloads in this kind of scenario sound sensible?

**Comment by whimboo** [comment]
Improving the error messages right now would be hard. Instead we should really do a refactoring of the code which is long outstanding and can help us with better messages.

For this specific case the [multilocale build failed](https://archive.mozilla.org/pub/mobile/nightly/2016/09/2016-09-25-03-02-26-mozilla-central-android-api-15/mozilla-central-android-api-15-nightly-bm74-build1-build45.txt.gz) and has not been retriggered. Maybe it was a permanent failure. It's hard to tell.

Would you mind telling me more about this unit testing framework? I would be interested because I maintain similar ones like for Firefox UI tests (Marionette) which gets done via mozmill-ci (https://github.com/mozilla/mozmill-ci). Feel free to drop me an email. Thanks!

I'm closing this issue given that there is no actionable item left over.
