### ISSUE TITLE
Add support for python 3

### ISSUE THREAD

**Issue by davehunt** [mozilla/mozdownload#415]
As support for python 2.7 is going to be dropped in 2020, we should prepare mozdownload to work against python 3.

**Comment by whimboo** [comment]
As a first step I would suggest that we import a set of future modules like:

> from __future__ import absolute_import, print_function, unicode_literals

This should help us while improving our code with Python 2.7 not to add new broken 3.x code.

Once all works for Python 3.x we should get it tested via Travis and AppVeyor.

**Comment by Nebelhom** [comment]
Hi,

If you guys don't mind, I will try my hand at this. 

I will follow this guide here: http://python-future.org/compatible_idioms.html

**Comment by whimboo** [comment]
Sounds great. Lets make sure to submit smaller commits which contain changes to a single type of change only. That would allow me to review the patches way faster.

**Comment by Nebelhom** [comment]
Agreed. I noticed that absolute_imports and unicode_literals have already been done in the files.

Based on the link above I would check for the following things first, to make sure it is not an issue:

* print_function
* Raising & Catching Exceptions
* Division (especially `//` for integer division)
* Metaclasses
* Dictionaries
* Custom classes
* Lists vs. iterators

I cannot say which of the above needs fixing, but I will check. If needed, I will first create an issue by bullet point and link it to this issue. The I will submit a PR... or if someone else wants to take one of the bullet points, please adhere to the same procedure ;)

**Comment by whimboo** [comment]
I think that sounds fine. Beside that there is no reason to file other issues for each individual item. Just create a single pull request and add separate commits for each of those areas.

**Comment by whimboo** [comment]
Otherwise we can also do multiple PRs for this issue if that makes it easier for you.

**Comment by Nebelhom** [comment]
I suggested to do it this because I thought it would be easiest for you to review it. Having many commits for each change in one PR feels difficult for me to debug.

I would prefer multiple PRs tied to this issue. I will just subdivide them...

**Comment by Nebelhom** [comment]
@whimboo Before I start with this, what is our philosophy on importing from `__future__`?

Do we only import when it is necessary inside the function, or do we do a blanket import of all modules in each file to proactively prevent any py27 -> py3 bugs from occurring..

Example print_function:
Print is not called in the function, so we leave the import out. 2 months later someone adds a print statement the py27 way and it is quietly accepted only to fail when we switch completely in 2020.

I ask, because I have seen that in [errors.py](https://github.com/mozilla/mozdownload/blob/master/mozdownload/errors.py) we do not import the absolute_imports. I was wondering if this was an oversight or on purpose..

**Comment by whimboo** [comment]
I would say that we import whats needed. This is also the only way for you to update our code step by step for the necessary changes. We make use of that also in the gecko tree, so I think that this is the right solution. If a module misses an import please add it appropriately. Thanks.

**Comment by Nebelhom** [comment]
Hi @whimboo,

I know it sounds silly, but I'll ask anyways: "How do I know which import is 'needed'?"

I've played around with trial and error imports to see if I get error messages that need fixing. I tried to use `futurize`, which broke all sorts of coding style rules in the process.

In both instances, I could not arrive at a satisfactory method to find out whether an import in a file is needed or not.

you mentioned the gecko code. What is the approach over there? Do you have a good example?

Thanks a lot :)

**Comment by whimboo** [comment]
Check the code for mozbuild. It makes use of all that a lot. You should find some good examples there what specifically to import. 

https://dxr.mozilla.org/mozilla-central/source/python/mozbuild/mozbuild/

Best is to figure out which future imports exists and which we would need. Then do PRs for each additonal import?

**Comment by Nebelhom** [comment]
Hi @whimboo 

I looked further into this issue and after running a tox in a python3 environment (thx @davehunt for showing me how to ;) ), I noticed that it raises some mozfile errors (see 2 examples below).

Will mozfile be changed to python3 any time soon or do we need to find an alternative to that if we want to become python3 compatible?

Traceback:

```
(mozdownload) nebelhom@nebelhom-TravelMate-P273:~/Mozilla/mozdownload/mozdownload$ tox -e py35
GLOB sdist-make: /home/nebelhom/Mozilla/mozdownload/mozdownload/setup.py
py35 inst-nodeps: /home/nebelhom/Mozilla/mozdownload/mozdownload/.tox/dist/mozdownload-1.21.zip
py35 installed: appdirs==1.4.0,mccabe==0.6.1,mock==2.0.0,mohawk==0.3.4,mozdownload==1.21,mozfile==1.2,mozinfo==0.9,mozprocess==0.24,packaging==16.8,pbr==1.10.0,progressbar==2.2,py==1.4.32,pycodestyle==2.3.1,pydocstyle==1.1.1,pyflakes==1.5.0,pylama==7.3.3,pyparsing==2.1.10,pytest==3.0.6,redo==1.5,requests==2.9.1,requests-hawk==1.0.0,six==1.10.0,treeherder-client==3.0.0,wptserve==1.4.0
py35 runtests: PYTHONHASHSEED='2707863130'
py35 runtests: commands[0] | pylama mozdownload
py35 runtests: commands[1] | py.test
========================================================================== test session starts ===========================================================================
platform linux -- Python 3.5.2, pytest-3.0.6, py-1.4.32, pluggy-0.4.0
rootdir: /home/nebelhom/Mozilla/mozdownload/mozdownload, inifile: 
plugins: pylama-7.3.3
collected 1 items / 27 errors 

================================================================================= ERRORS =================================================================================
______________________________________________________________ ERROR collecting tests/mozhttpd_base_test.py ______________________________________________________________
.tox/py35/lib/python3.5/site-packages/_pytest/python.py:418: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
.tox/py35/lib/python3.5/site-packages/py/_path/local.py:662: in pyimport
    __import__(modname)
<frozen importlib._bootstrap>:969: in _find_and_load
    ???
<frozen importlib._bootstrap>:958: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:664: in _load_unlocked
    ???
<frozen importlib._bootstrap>:634: in _load_backward_compatible
    ???
.tox/py35/lib/python3.5/site-packages/_pytest/assertion/rewrite.py:216: in load_module
    py.builtin.exec_(co, mod.__dict__)
tests/mozhttpd_base_test.py:14: in <module>
    import mozfile
.tox/py35/lib/python3.5/site-packages/mozfile/__init__.py:7: in <module>
    from .mozfile import *
E     File "/home/nebelhom/Mozilla/mozdownload/mozdownload/.tox/py35/lib/python3.5/site-packages/mozfile/mozfile.py", line 57
E       print "src: %s" % src
E                     ^
E   SyntaxError: Missing parentheses in call to 'print'
________________________________________________________ ERROR collecting
tests/cli/test_output.py ________________________________________________________________
ImportError while importing test module '/home/nebelhom/Mozilla/mozdownload/mozdownload/tests/cli/test_output.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/cli/test_output.py:4: in <module>
    from mozdownload import __version__, cli
.tox/py35/lib/python3.5/site-packages/mozdownload/__init__.py:7: in <module>
    from mozdownload import cli
.tox/py35/lib/python3.5/site-packages/mozdownload/cli.py:16: in <module>
    from mozdownload import factory, scraper
.tox/py35/lib/python3.5/site-packages/mozdownload/factory.py:9: in <module>
    from mozdownload import scraper
.tox/py35/lib/python3.5/site-packages/mozdownload/scraper.py:15: in <module>
    from urlparse import urlparse
E   ImportError: No module named 'urlparse'

```

**Comment by davehunt** [comment]
mozdownload depends on mozinfo, the the tests depend on mozfile and mozprocess. These packages belong to mozbase, which does not yet support Python 3. Furthermore, these packages are not used or testing in Python 3 environments. We would either need to explore alternatives, or mark this issue as dependent on one for mozbase to be upgraded to support Python 3. If you are interested, this would be a very valuable contribution, however I think the first part to take on would be to create an environment where we would test these packages using Python 3. Without this, there would be no guarantee that support for Python 3 wouldn't regress. It looks like this was [raised 2 years ago](https://bugzilla.mozilla.org/show_bug.cgi?id=1093212), but little work has been done.

**Comment by Nebelhom** [comment]
Hi @davehunt and @whimboo

I am in general interested in doing that, however, this sounds like a fair bit of work. Judging by my recent output, I am wondering whether this would be better suited to an intern of yours or something like that.

You are the better judges of the workload this takes.

**Comment by whimboo** [comment]
I think updating mozbase packages for some `__future__` imports should be an easy going route. Especially like the above listed print styles. It's really easy and should not take that long. Various scripts in [mozbuild](https://dxr.mozilla.org/mozilla-central/source/python/mozbuild/mozbuild/mach_commands.py) are already doing that, and we could mirror. Then once fixed I can release new packages. How does that sound for you?

**Comment by Nebelhom** [comment]
@whimboo Once I have time again, I will look into that. The next couple of weeks are quite busy.

The most important thing for me is to set up a valid test case that I can work with, so I have visibility. Is there a webpage that outlines how to set something like this for mozbase?

Thanks :)

**Comment by whimboo** [comment]
I think mozbase related questions we should move to the appropriate bug. But just a quick reply on that might not hurt... Tests for mozbase can be run through `./mach python-test testing/mozbase`. The appropriate [wiki page](https://wiki.mozilla.org/Auto-tools/Projects/Mozbase) hasn't been updated yet for it, but that should hopefully be done soon.

**Comment by whimboo** [comment]
I have just another idea to speed things up for this project. Why don't we get rid of the `mozinfo` dependency? It looks like it's the only one which is bases on `mozbase` and is blocking us with the conversion. I really don't want to wait for mozbase.

For the tests we might easily be able to get rid of `mozfile` too. Even a replacement for `mozprocess` should be not that hard to do.

**Comment by whimboo** [comment]
FYI the mozinfo package got already fixed for Python 3 support via [bug 1426330](https://bugzilla.mozilla.org/show_bug.cgi?id=1426330) but hasn't been released yet.

**Comment by peterbe** [comment]
For what it's worth, I made this: https://github.com/choller/mozbase/pull/1
I'm not even sure if that's the right repo but it definitely makes `mozinfo` Python 3 (and 2 backwards) compatible.

**Comment by peterbe** [comment]
I managed to install a working firefox 61 inside a docker container using a hacked version of `mozdownload`. To make it work I had to edit a couple of files that are outside this project such as `mozinfo` and `mozfile`. These changes were really trivial. For what it's worth, we could copy mozinfo *into* this repo and that being a version that works in 2 and 3. And equally do something like that with mozfile. Thoughts and ideas?

**Comment by peterbe** [comment]
I got pretty far but stumbled on `wptserve`. It's not py 3 compatible either.

**Comment by whimboo** [comment]
Sorry that I have to say that your work here was based on a very outdated repository on Github. As it has been made clear via https://github.com/mozilla/mozbase-deprecated the repository is closed, and any further development happens in [mozilla-central/testing/mozbase](http://dxr.mozilla.org/mozilla-central/source/testing/mozbase/). It means that the Github repo is outdated since 2 full years.

Meanwhile lots of work also in the direction of Python3 has been done for mozbase. @davehunt is mostly driving those efforts also with the community. The current status and work left to do, can be seen on [bug 1093212](https://bugzilla.mozilla.org/show_bug.cgi?id=1093212). So if you aren't that disappointed now, we would highly welcome you to work on such a left-over bug. 

How does it sound for you @peterbe?

And again I feel very sorry that this all was not that clear, and you spent time on that outdated mozbase code.

**Comment by peterbe** [comment]
> And again I feel very sorry that this all was not that clear, and you spent time on that outdated mozbase code.

It really wasn't that much time. I did a `pip install mozdownload` and tried to run it, got errors, edited the .py files directly until it worked in Py3 and thought "Perhaps I should share this", tried to run the test suite, got nasty errors, gave up and switched to [get-firefox](https://www.npmjs.com/package/get-firefox).

I've ported many projects to py3 and it's surprisingly easy these days with good tools like tox and Stackoverflow posts but the tedious thing is orchestrating dependencies etc and it looks like https://bugzilla.mozilla.org/show_bug.cgi?id=1093212 is doing a great job of that. 

Happy to help if anything comes up. For now, that `get-firefox` will suffice for my needs.

**Comment by whimboo** [comment]
Ok, that is at least good to hear. I already thought that you spent a fair amount of time here.

In case of interest in helping with Python 3 support, feel free to check one of the dependency bugs on Bugzilla. As earlier the required mozbase packages have py3 support, as earlier we can update mozdownload to also be py3 compatible.

Also, I started to convert some of the mozdownload tests to pytest, which cover Firefox and Fennec under the remote subfolder. If you have interest you could convert some others, especially those which make use of `mozfile`. It seems to be only used for tests, which have to handle temporary files. With pytest it can be done more elegantly via the [tmpdir](https://docs.pytest.org/en/latest/tmpdir.html) fixture.

**Comment by AndreiH** [comment]
I have opened PR: https://github.com/mozilla/mozdownload/pull/536 for review
Please let me know what you think and if there is something else that should be added.
Thanks !

**Comment by AndreiH** [comment]
Python 3 compatibility ready for a full review https://github.com/mozilla/mozdownload/pull/536
Fixed all tests and added Python 3 runs on Appveyor and Travis CI.
Feedback is welcomed. Thanks !

**Comment by whimboo** [comment]
The PR #536 just got merged into master and as such Py3 support will be present with the next release of mozdownload!
