### ISSUE TITLE
pylama failures

### ISSUE THREAD

**Issue by Nebelhom** [mozilla/mozdownload#418]
In PR #412, we are seeing a bunch of pylama failures in appveyor and travis.

Before we can land the above PR we need to resolve those issues.

Minimal suggestionon what to do are to add at least a config file for pylama including an allowed line-length of 100 chars instead of 80 only.

**Comment by Nebelhom** [comment]
@whimboo This issue should block #412 until resolved.

**Comment by whimboo** [comment]
PR #419 got merged.
