### ISSUE TITLE
Failure in test_optional_authentication: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozdownload#420]
It looks like that https://webqa-ci.mozilla.com/ is no longer a valid URL. If we want to continue with optional basic authentication we should use the following URL instead:

http://www.mozqa.com/data/mozqa.com/http_auth/basic/

@Nebelhom, do you want to get this fixed?

**Comment by Nebelhom** [comment]
Hi whimboo,

I will look into it. Issue is that http://www.mozqa.com/data/mozqa.com/http_auth/basic/ is already the URL that is used for testing.

https://github.com/mozilla/mozdownload/blob/master/tests/base_scraper/test_base_scraper.py#L81

Do we have another option?

Thanks :)

**Comment by whimboo** [comment]
Lets get this test removed. Given that basic auth works we can implicitly say that it will also work for optional auth.

**Comment by whimboo** [comment]
PR #421 got merged.
