### ISSUE TITLE
Add support for pyup.io

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozdownload#424]
Pyup.io can be used to stay up2date with dependencies. It will automatically issue pull requests with details about news in that version. See https://github.com/mozilla/PyPOM/pull/17 for example.

**Comment by whimboo** [comment]
This is finally done now given that I totally missed to do it in all the last months. The initial PR from pyup.io is here: https://github.com/mozilla/mozdownload/pull/448

**Comment by whimboo** [comment]
@davehunt, as it looks like pyup.io only proposed updates for the packages as required for tox. What would we have to change so it also checks the mozdownload dependencies?

**Comment by davehunt** [comment]
@whimboo see the discussion in https://github.com/pyupio/pyup/issues/137

**Comment by whimboo** [comment]
Ok, so that means we would have to create a `requirements.txt` file with the list of packages and versions, and read it inside of setup.py. We already do that for various other projects, so that shouldn't be a complex change. For example check: https://hg.mozilla.org/mozilla-central/file/default/testing/marionette/client/setup.py#l48

@Nebelhom would you be interested to make this change?

**Comment by Nebelhom** [comment]
Hi @whimboo Thanks for highlighting. I will give it a go.

**Comment by whimboo** [comment]
I merged PR #450. Thank you a lot Johannes! Lets see how it works...
