### ISSUE TITLE
E722 (No bare excepts) needs to be fixed

### ISSUE THREAD

**Issue by Nebelhom** [mozilla/mozdownload#426]
An update in pycodestyle causes pylama in scraper.py to fail with E722.

This needs to be fixed. For the moment this will be ignored in setup.cfg, but we should really fix this.

**Comment by whimboo** [comment]
Ups. I had merge issue when I was working on PR #429. So I fixed that because it was not listed as a warning. But what I missed is to remove the comment. I can just push a comment only fix for that.

**Comment by whimboo** [comment]
PR #432 got merged.
