### ISSUE TITLE
Wrong build number displayed for candidate build

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozdownload#437]
Just run the following command to see the broken output. Luckily we still download the correct version.

```
% mozdownload -t candidate -v 53.0
INFO | Retrieving list of candidate builds from https://archive.mozilla.org/pub/firefox/candidates/53.0-candidates/
INFO | Found 4 builds: build1, build3, build5, build6
INFO | Selected build: build4
INFO | Downloading from: https://archive.mozilla.org/pub/firefox/candidates/53.0-candidates/build6/mac/en-US/Firefox%2053.0.dmg
INFO | Saving as: /Volumes/data/code/mozdownload/firefox-53.0-build6.en-US.mac.dmg
```

I assume that we print the index of the build but not the actual name what we should do.

**Comment by ujjwalwahi** [comment]
Hi @whimboo I would like to work on this issue

**Comment by whimboo** [comment]
Sure. You are welcome to work on this issue @ujjwalwahi. Let me know if you have questions.

PS: Make sure that it is still a problem.

**Comment by ujjwalwahi** [comment]
@whimboo I checked and it was still displaying incorrect info for selected build. Created pull request for the same.
