### ISSUE TITLE
mozdownload can't download nightly debug builds

### ISSUE THREAD

**Issue by EricRahm** [mozilla/mozdownload#438]
This is probably fallout from the whole "we don't put builds on archive.m.o anymore" debacle.

> mozdownload --debug-build -t daily
> INFO | Retrieving the build status file from https://archive.mozilla.org/pub/firefox/nightly/latest-mozilla-central/
> INFO | Retrieving list of builds from https://archive.mozilla.org/pub/firefox/nightly/2017/04/
> Traceback (most recent call last):
>   File "/home/erahm/dev/tmp/dmd_test/bin/mozdownload", line 11, in <module>
>     sys.exit(cli())
>   File "/home/erahm/dev/tmp/dmd_test/local/lib/python2.7/site-packages/mozdownload/cli.py", line 165, in cli
>     build = factory.FactoryScraper(scraper_type, **kwargs)
>   File "/home/erahm/dev/tmp/dmd_test/local/lib/python2.7/site-packages/mozdownload/factory.py", line 125, in __init__
>     scraper_types[scraper_type].__init__(self, **kwargs)
>   File "/home/erahm/dev/tmp/dmd_test/local/lib/python2.7/site-packages/mozdownload/scraper.py", line 344, in __init__
>     Scraper.__init__(self, *args, **kwargs)
>   File "/home/erahm/dev/tmp/dmd_test/local/lib/python2.7/site-packages/mozdownload/scraper.py", line 133, in __init__
>     self._retry_check_404(self.get_build_info)
>   File "/home/erahm/dev/tmp/dmd_test/local/lib/python2.7/site-packages/mozdownload/scraper.py", line 148, in _retry_check_404
>     self._retry(func, **retry_kwargs)
>   File "/home/erahm/dev/tmp/dmd_test/local/lib/python2.7/site-packages/mozdownload/scraper.py", line 139, in _retry
>     return redo.retry(func, **retry_kwargs)
>   File "/home/erahm/dev/tmp/dmd_test/local/lib/python2.7/site-packages/redo/__init__.py", line 162, in retry
>     return action(*args, **kwargs)
>   File "/home/erahm/dev/tmp/dmd_test/local/lib/python2.7/site-packages/mozdownload/scraper.py", line 401, in get_build_info
>     self.date, self.build_index)
>   File "/home/erahm/dev/tmp/dmd_test/local/lib/python2.7/site-packages/mozdownload/scraper.py", line 482, in get_build_info_for_date
>     raise errors.NotFoundError(message, url)
> mozdownload.errors.NotFoundError: Folder for builds on 2017-04-25-10-15-37 has not been found: https://archive.mozilla.org/pub/firefox/nightly/2017/04/

**Comment by whimboo** [comment]
This is basically [bug 1360550](https://bugzilla.mozilla.org/show_bug.cgi?id=1360550), and not an issue with mozdownload.
