### ISSUE TITLE
Update to treeherder-client 4.0.0

### ISSUE THREAD

**Issue by edmorley** [mozilla/mozdownload#441]
Currently the range in setup.py is `treeherder-client >= 3.0.0, <4.0.0`:
https://github.com/mozilla/mozdownload/blob/838413b5b12b06a78592514ccf008aa89b7f8f4f/setup.py#L31

Please can you bump to `treeherder-client >= 4.0.0, <5.0.0`.

For the changes, see:
https://bugzilla.mozilla.org/show_bug.cgi?id=1387711#c2

**Comment by whimboo** [comment]
I assume you mean `treeherder-client >= 4.0.0, <5.0.0`

**Comment by edmorley** [comment]
Ah yes, I forgot to update after copy-pasting. Have fixed the above now :-)

**Comment by whimboo** [comment]
I would like to squeeze this into the upcoming 1.23 release. A PR should be up in a moment.

**Comment by whimboo** [comment]
PR #447 has been merged.
