### ISSUE TITLE
Scrolling broken on Thunderbird 52.5.0 32 bit

### ISSUE THREAD

**Issue by 7--** [mozilla/mozdownload#458]
When you add an email account to thunderbird and scroll down it will not load older emails rather it does nothing. My setting already specify to download all emails from all folder and my email is syncoronized. Hope you can fix in the next version.

**Comment by whimboo** [comment]
This repository is not related to Thunderbird and possible defects. You want to check for known issues by consulting https://support.mozilla.org/en-US/products/thunderbird or by filing a new bug under https://bugzilla.mozilla.org/enter_bug.cgi?product=Thunderbird&component=General
