### ISSUE TITLE
Convert unit tests to plain pytest

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozdownload#468]
All of our tests for mozdownload still make use of the Python unittest framework, which is not necessary because pytest is used to execute all the tests. As such we should get rid of the test classes, and instead use fixtures. In https://github.com/mozilla/mozdownload/pull/467/commits/e0c9484b3a875cde305c59bd7ed5789c5410d179 I already converted `remote/test_firefox.py`.

We should do the same for all the remaining tests in the following sub folders: 

- [x] base_scraper
- [x] cli
- [x] daily_scraper
- [x] direct_scraper
- [x] directory_parser
- [x] factory
- [x] release_candidate_scraper
- [x] release_scraper
- [x] remote
- [x] tinderbox_scraper
- [x] treeherder
- [x] try_scraper

If you want to work on the fennec or thunderbird test please let us know here, and push a PR for only one of both at a time. That way we can divide the work. Thanks.

Once all of the above are done we can safely remove the `MozHttpdBaseTest` class in https://github.com/mozilla/mozdownload/blob/master/tests/mozhttpd_base_test.py.

**Comment by danishprakash** [comment]
Hi @whimboo, as is visible in this issue that there has been a lot of activity on this, is this issue still active, can I take this up?

**Comment by Utkarsh1308** [comment]
Can I work on this issue?

**Comment by Utkarsh1308** [comment]
Please review https://github.com/mozilla/mozdownload/pull/521

**Comment by Utkarsh1308** [comment]
What exactly do I have to do? Sorry I'm fairly new to open source. Do you mean converting other tests to pytests now that we are done with the remote tests?

**Comment by whimboo** [comment]
That is correct. If you don't mind you could pick another subfolder, and convert all of the tests to pytest. If you face problems please let me know. Thanks!

**Comment by Utkarsh1308** [comment]
Thanks! Then I would be starting with release_candidate_scraper tests

**Comment by Utkarsh1308** [comment]
Could you help me with this error - NotFoundError: Specified build has not been found: https://archive.mozilla.org/pub/firefox/candidates/23.0.1-candidates/

Here are the changes I made:
https://github.com/Utkarsh1308/mozdownload/blob/bugFix/tests/release_candidate_scraper/test_release_candidate_scraper_indices.py

**Comment by whimboo** [comment]
As the failure shows you are using a remote HTTP server for the tests now which doesn't work. Everything beside the remote tests are using a local server instead. You removed it with your latest changes. 

It means that you will need a pytest fixture which can be used by tests to set the server up, and get a reference to it. This could be best done when you create a new file called `conftest.py` and place it directly in the `tests` folder. How fixtures work is explained here: https://docs.pytest.org/en/latest/fixture.html

**Comment by Utkarsh1308** [comment]
In conftest.py How am I supposed to set up a local server. Is there any documentation for mhttpd_base_test. I looked at the documentation and the fixture is using an smtp connection. Should I use that?

**Comment by whimboo** [comment]
Using a local HTTP server reduces the risk of having flaky tests due to network issues. This could cause timeouts when loading the test pages, or in our case the various files which are mocking real files. 

To get that server running create a fixture and use the following code:

https://github.com/mozilla/mozdownload/blob/master/tests/mozhttpd_base_test.py#L30-L34

Then you can yield the server instance inside the fixture, which actually will make it available for the test using that fixture.

Also note that with pytest we won't need the `MozHttpdBaseTest` class at all, given that the above fixture handles the local server, and pytest internally has the `tempdir` fixture.

**Comment by Utkarsh1308** [comment]
What does the cls argument mean in the class function. On running my fixture using pytest, I got the error - fixture 'cls' not found.

**Comment by Utkarsh1308** [comment]
Could you explain why is my test failing now?

conftest.py - https://github.com/Utkarsh1308/mozdownload/blob/bugFix/tests/conftest.py
test - https://github.com/Utkarsh1308/mozdownload/blob/bugFix/tests/release_candidate_scraper/test_release_candidate_scraper_indices.py

**Comment by whimboo** [comment]
Would you mind to create a pull request for those changes? That would allow me to see the failures on Travis CI, and comment appropriately.

**Comment by Utkarsh1308** [comment]
Please review https://github.com/mozilla/mozdownload/pull/523. Travis is failing at a different test, but the other test are passing.

**Comment by whimboo** [comment]
Again, please create a PR so that we can work out specifics there. Without seeing your changes I cannot help at all. Sorry.

**Comment by rgpt** [comment]
As discussed with @whimboo I will help on this issue and start working
on the try scraper tests.

**Comment by rgpt** [comment]
> In test_release_candidate_scraper_latest.py I'm getting some kind of error on calling scraper.filename
> 
> ```
> AttributeError: 'LocalPath' object has no attribute 'rfind'
> ```
> How do I fix this?

try putting tmpdir in str() [here-ReleaseCandidatefunction](https://github.com/Utkarsh1308/mozdownload/commit/8aae0381c66761b05d54ca7a27f6fe574060a3c3#diff-6362f8c4d63c2f53e3d8fe6e2cff9362R103). 
Check if this solves the problem you are facing. I was facing similar issue solved it using this.

**Comment by whimboo** [comment]
@rgpt, we got this problem already fixed and the appropriate code landed. Also thanks for picking another subfolder for conversation!

@Utkarsh1308 please let us know if you want to continue the work here, or work on another issue. Thanks!

**Comment by rgpt** [comment]
@whimboo should i start porting other subfolders too. Can you suggest if there is any specific priority among them i mean, which ones should i take up first ?

**Comment by whimboo** [comment]
@rgpt it's fine when you start with the one we discussed earlier. Once the PR is up, feel free to also pick another one. There is no specific priority, but just let us know here which one you want to work on.

**Comment by Utkarsh1308** [comment]
@whimboo I can do a couple more tests. I also wanted to contribute to some other repos of mozilla using bugzilla. I was wondering if you could guide me on how to do that. I had some trouble understanding how mercurial and phabricator works.

**Comment by whimboo** [comment]
@Utkarsh1308 sounds good. Select what you actually want, and where you can learn most. Feel free to also pick another issue on this repository.

In regards of other projects I would propose to check the following page: https://codetribute.mozilla.org/projects/automation. If you find something for Marionette, and geckodriver I can help. Otherwise other people mentor those bugs, and will also help you out with questions.

**Comment by rgpt** [comment]
I wish to take up `base scraper` and `direct scraper` together as next folders to port once i am done with  #528.

> @rgpt it's fine when you start with the one we discussed earlier. Once the PR is up, feel free to also pick another one. There is no specific priority, but just let us know here which one you want to work on.

**Comment by whimboo** [comment]
@rgpt, that is great. Don't feel blocked with the review on the other PR. If you want already start on those two scrapers.

**Comment by rgpt** [comment]
@whimboo, no problems at all, I have started working on the other files. I will make the mentioned changes as you asked. There is a profuse amount of learning that is associated with the changes that you ask me to do which is really helpful.

**Comment by rgpt** [comment]
@whimboo 
https://github.com/mozilla/mozdownload/blob/master/tests/base_scraper/test_base_scraper.py#L44 - i just wanted to know - `HERE` will be replace to what?, and moreover in place of `self.WDIR` we will keep `httpd.get_url()` which is a url. So it will be like `folderlocation+Url+folderLocation` which is wrong. Moreover it is sort of test like resources from where we are downloading and resources which we have downloaded - whether md5 of that matches or not but as one is on server and other in local. so create md5 at L44 (as in the link) will sure to fail. Need help in modifiying this case.

**Comment by whimboo** [comment]
@rgpt here some links. I think you can get it working via `httpd.router.doc_root`:

https://dxr.mozilla.org/mozilla-central/rev/c2593a3058afdfeaac5c990e18794ee8257afe99/testing/web-platform/tests/tools/wptserve/wptserve/server.py#639
https://dxr.mozilla.org/mozilla-central/rev/c2593a3058afdfeaac5c990e18794ee8257afe99/testing/web-platform/tests/tools/wptserve/wptserve/router.py#98

**Comment by rgpt** [comment]
I wish to take up `daily_scraper` as next.

**Comment by rgpt** [comment]
I will be taking directory parser and factory up next once i am done with the #530, #532

**Comment by Utkarsh1308** [comment]
I closed https://github.com/mozilla/mozdownload/pull/531 by mistake. Can you repoen it

**Comment by Adarsh-Shrivastava-001** [comment]
Hi @whimboo I am new to open source programming, but quite experienced in Python programming. Please guide me how can I contribute here.

**Comment by whimboo** [comment]
Welcome @vipulchhabra99 and @Adarsh-Shrivastava-001 to our community! If you want to contribute to this particular issue please check the very first comment, and pick one of the not taken yet test sub directories. Once done please add a comment so that we are aware of which you have chosen. Thanks.

**Comment by whimboo** [comment]
Btw. directories left are cli, directory_parser, factory, treeherder.

**Comment by rgpt** [comment]
@whimboo I wish to take up `Cli`, `treeherder` up next. I have requested PR for `directory_parser` and `factory`.

**Comment by whimboo** [comment]
Sounds good @rgpt! Looks like those are the last remaining folders to convert. \o/

**Comment by rukkykf** [comment]
hello, I'd like to work on the factory directory.....is that still available?

**Comment by whimboo** [comment]
Sorry, but all the sub directories have been covered already. The last PR is under review and will be merged soon. If you are still interested please have a look at one of the other issues. I'm basically open to mentor everything. But it depends on your experience with Python, and the complexity of the issue.

**Comment by whimboo** [comment]
@rgpt would you mind to come up with a final PR for removing the `MozHttpdBaseTest` class, and no longer needed PyPI dependencies?

**Comment by rgpt** [comment]
Sure @whimboo I will work on that and submit a final PR.

**Comment by whimboo** [comment]
This is all done now. Thanks a lot everyone who was involved into this effort!

**Comment by rgpt** [comment]
Thank You @whimboo :) 
> This is all done now. Thanks a lot everyone who was involved into this effort!

**Comment by whimboo** [comment]
Hello @rgpt. It's been a while since I have heard last from you. So given the great work you did I wonder if you are interested to continue with your contribution to the mozdownload code? We have a couple of other issues which would need some coding love, and which can be used to increase your skill set.  Just let me know. Thanks!
