### ISSUE TITLE
Convert unit tests in cli to use pytest

### ISSUE THREAD

**Issue by venkateshpitta** [mozilla/mozdownload#487]
Similar to issue #486 moving from Python unittest framework to pytest, because pytest is used to run tests for mozdownload.

Since there are four files in the directory [https:github.com/mozilla/mozdownload/tree/master/tests/cli/](https://github.com/mozilla/mozdownload/tree/master/tests/cli/), it may be a good idea to submit one PR per file so that work can be done on small patches, one at a time.

**Comment by whimboo** [comment]
We actually don't need a new issue for each of the sub folders. Lets create all PRs with a reference to #486.
