### ISSUE TITLE
NotFoundError instead of RequestException in base_scraper test 

### ISSUE THREAD

**Issue by rgpt** [mozilla/mozdownload#534]
When not able to download the package it should result into NotFoundError and not Request Exception error as the test case was specifically designed for `doesnotexist` Case.
Reference -https://github.com/mozilla/mozdownload/blob/f8474674808b3ded69354f8a09da208c03691aaf/tests/base_scraper/test_base_scraper.py#L55

**Comment by whimboo** [comment]
Thanks a lot for filing the issue @rgpt.

**Comment by apu1995** [comment]
Hi @whimboo I have been looking at the test script. Can I take this up ?
scraper1.download is to be asserted with does not exist exception which could probably be HTTP Error (404 not found) from the request module or may be we can go with custom exception.
Please let me know what needs to be done over here ?

**Comment by whimboo** [comment]
Yes, you can take this. In regards of the requests exception please check which possible types could be raised. I'm fairly sure there is a specific exception for not found. This needs to be caught and converted into a NotFoundError.

**Comment by apu1995** [comment]
@whimboo I was going through the file. And found this. 

https://github.com/mozilla/mozdownload/blob/f8474674808b3ded69354f8a09da208c03691aaf/mozdownload/scraper.py#L143
This case has been handled while downloading.
If you want something else please let me know.  
Otherwise, we may have to do something similar

**Comment by whimboo** [comment]
I would suggest that you first update the base scraper test for the expected not found exception. Then have a look which specific requests exception including its status code get raised.

**Comment by thisisshub** [comment]
Is this issue still going on? If it is, can I take it up?

**Comment by whimboo** [comment]
We haven't heard back from @apu1995 for over a month. So I would say just get started, and let me know if you need some help. Thanks for your interest!

**Comment by thisisshub** [comment]
> We haven't heard back from @apu1995 for over a month. So I would say just get started, and let me know if you need some help. Thanks for your interest!

Thanks for the reply, I'll get started right away.

**Comment by whimboo** [comment]
Thanks @thisisshub. I will have a look at your PR #588 soon.

**Comment by thisisshub** [comment]
yes thank you @whimboo. I am facing some issues in #588 and would love your guidance over there

**Comment by kaushiksk** [comment]
@whimboo Kindly review my PR
