### ISSUE TITLE
Add "remote" pytest marker for remote tests and only run those tests in CI

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozdownload#543]
With issue #468 fixed soon, we can now mark specific functions to be not run by default when testing locally, but only when checks run in CI. This specifically applies to all the remote tests in https://github.com/mozilla/mozdownload/tree/master/tests/remote. 

A [pytest marker](https://docs.pytest.org/en/latest/example/markers.html) should be added for each of those tests, and registered in the pytest.ini file.

By default those tests should not be run, but only when being executed in CI (Travis CI, AppVeyor). To get this done their appropriate configuration (yaml) files need to be updated.

**Comment by ali-alsabbah** [comment]
I'd be interested in doing this if I can get a little help

**Comment by whimboo** [comment]
Absolutely! Let me know when you have questions, or also join us on irc.mozilla.org in the #automation channel for direct help. Thanks!

**Comment by snowmanstark** [comment]
@whimboo Can I start working on this issue if it is not assigned to anyone?

**Comment by whimboo** [comment]
@snowmanstark, sorry for the late reply but I missed your question here. You could have been started, but now we already have PR #572, which adds this feature. If you want to work on something else I would be still happy to mentor you.

**Comment by snowmanstark** [comment]
Thanks @whimboo for the update! Will let you know when I would need mentoring.

**Comment by whimboo** [comment]
Fixed by PR #572. Thanks a lot!
