### ISSUE TITLE
Add support for downloading Firefox for Android (Fenix)

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozdownload#624]
Given that the Fennec project is no longer available for quite some Firefox releases and got replaced with Fenix (GeckoView) we have to add support for downloading Fenix builds from archive.mozilla.org:

https://archive.mozilla.org/pub/fenix/

**Comment by whimboo** [comment]
Hi @salilmishra23! With your great help in getting Github Actions to run I wonder if you might be interested to work on this particular issue? It shouldn't be too hard given that it mainly only involves adding a new product, which then can benefit from all the other already existing code.

Please let me know. TIA!

**Comment by Karthik-PM** [comment]
can i work on this issue

**Comment by whimboo** [comment]
Feel free to get started. It shouldn't be too hard given that you might be able to copy most of the Fennec specific handling for Fenix. Let me know if you got stuck or have questions. Thanks!

**Comment by Karthik-PM** [comment]
thank you !!!

**Comment by whimboo** [comment]
Hi @Kart121. I wanted to check back with you if you are still interested to work on this issue. I would like to have this feature in the next release of mozdownload given that the Selenium project has shown interest. Can you please let me know where you are and what's blocking you from creating a PR? Thanks.

**Comment by Kart121** [comment]
i am so sorry @whimboo i have been having my internal evaluations and projects which will end by the end of this week .

**Comment by whimboo** [comment]
Thanks a lot for the feedback @Kart121! Does it mean that you would still have interest to start your contribution for this particular issue? Depending on your available time we could also find a smaller one for sure.

**Comment by Kart121** [comment]
unfortunately , i am not sure if i can make ends meet ... as i am not sure of how complex it will be for me as i am new to this repo.

**Comment by salilmishra23** [comment]
Hey @whimboo, I can work on this, just a question do we add `fenix` and keep `fennec` or we replace `fennec` with `fenix`?

**Comment by whimboo** [comment]
@salilmishra23 that would be great! And sorry for the late reply but I was out and just saw your comment now.

Generally we should leave `fennec` at least for now given that in some cases tools might still want to download those builds for regression tests. As such please duplicate what we have for `fennec` and make it available for `fenix`. Thanks!
