### ISSUE TITLE
Fallback to win32 builds on win64

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozdownload#67]
On all Windows 64bit machines we currently fail to download the build because it defaults to win64 builds which we currently don't ship. Lets default to win32 builds instead.

**Comment by whimboo** [comment]
Long time no update here. Soon we will ship win64 builds. Right now those are on beta:
ftp://ftp.mozilla.org/pub/firefox/releases/latest-beta/win64/

So I don't think that we should fix this issue anymore. It's simply outdated. @TLemur sorry for not updating it in time and that you wasted time for trying to fix it. :(

**Comment by TLemur** [comment]
@whimboo No problem, just can you answer my question in issue #108 please?
