### ISSUE TITLE
Update scraper class methods to return raw regular exceptions without inserting placeholders

### ISSUE THREAD

**Issue by davehunt** [mozilla/mozdownload#7]
This was originally raised on [bug 712253](https://bugzilla.mozilla.org/show_bug.cgi?id=712253):

> Currently nearly all of the regular expression class methods do not return raw regular expressions but already fill in values for the placeholders. All those instances have to be eliminated, because of [bug 704186](https://bugzilla.mozilla.org/show_bug.cgi?id=704186). Currently there is no way to get e.g. an URL for builds from another month without having to duplicate the code or update self.date, which is not an option at this point.

**Comment by whimboo** [comment]
I don't think it's worth spending time on this issue while scraping of data should be replaced with Taskcluster. See issue #365.
