### ISSUE TITLE
Add a dependabot configuration to update GitHub actions

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozdownload#702]
We should have a dependabot configuration for mozdownload to update GitHub actions to prevent manual work like on https://github.com/mozilla/mozdownload/pull/701.

See the following documentation for details:
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

**Comment by miguellords** [comment]
try this
https://bit.ly/4evXrQ6
If you don't have the c compliator, install it.(gcc or clang)
