### ISSUE TITLE
Add support to download a build by a given (relative) build range

### ISSUE THREAD

**Issue by davehunt** [mozilla/mozdownload#8]
This was originally raised as [bug 704186](https://bugzilla.mozilla.org/show_bug.cgi?id=704186):

> We can download a daily build given by a date or by latest. But something we additionally need is the feature to specify a range, so we can e.g. download the build before the specified one for update testing. This range will be relative and should work for all different ways we can specify builds.
> 
> Note: For the implementation we have to make sure the script will also work across year boundaries. That's something we haven't implemented yet.

**Comment by Tim-Smet** [comment]
I am new to contributing to open source. I am wondering if there is needed any help (anything. I am no experienced coder but want to gain experience) on this issue? I picked this issue from a list on Codetribute for Python because it was the longest open issue. So I thought it would be fun to contribute something to an issue that is open for quite some time.

**Comment by whimboo** [comment]
@Tim-Smet thank you for your interest in contributing. I'm happy to mentor, but noticed that this issue is blocked on issue #7. Maybe you want to take that other one instead?

**Comment by Tim-Smet** [comment]
@whimboo Thank you for the reply! I would love to give it a go, but I don't really know how to start or what I have to do? I hope you can guide me and pass on some wisdom.

**Comment by whimboo** [comment]
Sure, let me know on the other issue if you understand the problem, and we can get started.

**Comment by Tim-Smet** [comment]
Thanks a lot! Currently I am doing an internship, so I will do what I can in my spare time. Also This evening I start moving. Internet will be installed Monday afternoon. What I want to say is that of monday evening I will start working on it. Just to give a heads up.

**Comment by staranus** [comment]
Hi @whimboo, I would like to take the blocked issue. How can I contact you about that?

**Comment by whimboo** [comment]
Hey, so I had a look at the blocking issue and I don't think it's worth our time given that scraping for the builds will be replaced with Taskcluster support (see issue #365). As such I closed it.

Also regarding this issue it was important while we were running automated update tests for Firefox and needed a build from x days ago. This is not needed anymore, and as such I also wouldn't spend the time on getting this added. Clients could calculate the exact date on their own and feed it in via the `--date` argument.

@staranus if you want to work on something else instead please let me know on the appropriate issue. Thanks!
