### ISSUE TITLE
Allow specifying a full path to download the file to

### ISSUE THREAD

**Issue by davehunt** [mozilla/mozdownload#92]
With [bug 857037](https://bugzilla.mozilla.org/show_bug.cgi?id=857037) we will be removing support for running automation against binaries in a directory. Instead, automation will target a specific binary, but mozdownload does not currently support specifying the filename of the downloaded content.

We should add an `--target` option (and potentially remove the `--directory` option). If not specified we should download to the current directory. If a directory is specified we should retain the remote filename and download it to the specified local directory. If a full path and filename is specified then we should download to the specified local file.

**Comment by ujjwalwahi** [comment]
I would like to work on this

**Comment by whimboo** [comment]
Ujjwal, you are welcome! Let me know if you need help. Also in regards of the patch, we will need an automated test which verifies the functionality of the new feature. Thanks!

**Comment by whimboo** [comment]
PR #234 has been merged. Thanks a lot!
